namespace System.Net;

[global::__DynamicallyInvokable]
public enum HttpResponseHeader
{
	[global::__DynamicallyInvokable]
	CacheControl,
	[global::__DynamicallyInvokable]
	Connection,
	[global::__DynamicallyInvokable]
	Date,
	[global::__DynamicallyInvokable]
	KeepAlive,
	[global::__DynamicallyInvokable]
	Pragma,
	[global::__DynamicallyInvokable]
	Trailer,
	[global::__DynamicallyInvokable]
	TransferEncoding,
	[global::__DynamicallyInvokable]
	Upgrade,
	[global::__DynamicallyInvokable]
	Via,
	[global::__DynamicallyInvokable]
	Warning,
	[global::__DynamicallyInvokable]
	Allow,
	[global::__DynamicallyInvokable]
	ContentLength,
	[global::__DynamicallyInvokable]
	ContentType,
	[global::__DynamicallyInvokable]
	ContentEncoding,
	[global::__DynamicallyInvokable]
	ContentLanguage,
	[global::__DynamicallyInvokable]
	ContentLocation,
	[global::__DynamicallyInvokable]
	ContentMd5,
	[global::__DynamicallyInvokable]
	ContentRange,
	[global::__DynamicallyInvokable]
	Expires,
	[global::__DynamicallyInvokable]
	LastModified,
	[global::__DynamicallyInvokable]
	AcceptRanges,
	[global::__DynamicallyInvokable]
	Age,
	[global::__DynamicallyInvokable]
	ETag,
	[global::__DynamicallyInvokable]
	Location,
	[global::__DynamicallyInvokable]
	ProxyAuthenticate,
	[global::__DynamicallyInvokable]
	RetryAfter,
	[global::__DynamicallyInvokable]
	Server,
	[global::__DynamicallyInvokable]
	SetCookie,
	[global::__DynamicallyInvokable]
	Vary,
	[global::__DynamicallyInvokable]
	WwwAuthenticate
}
