namespace System.Net;

[global::__DynamicallyInvokable]
public enum HttpRequestHeader
{
	[global::__DynamicallyInvokable]
	CacheControl,
	[global::__DynamicallyInvokable]
	Connection,
	[global::__DynamicallyInvokable]
	Date,
	[global::__DynamicallyInvokable]
	KeepAlive,
	[global::__DynamicallyInvokable]
	Pragma,
	[global::__DynamicallyInvokable]
	Trailer,
	[global::__DynamicallyInvokable]
	TransferEncoding,
	[global::__DynamicallyInvokable]
	Upgrade,
	[global::__DynamicallyInvokable]
	Via,
	[global::__DynamicallyInvokable]
	Warning,
	[global::__DynamicallyInvokable]
	Allow,
	[global::__DynamicallyInvokable]
	ContentLength,
	[global::__DynamicallyInvokable]
	ContentType,
	[global::__DynamicallyInvokable]
	ContentEncoding,
	[global::__DynamicallyInvokable]
	ContentLanguage,
	[global::__DynamicallyInvokable]
	ContentLocation,
	[global::__DynamicallyInvokable]
	ContentMd5,
	[global::__DynamicallyInvokable]
	ContentRange,
	[global::__DynamicallyInvokable]
	Expires,
	[global::__DynamicallyInvokable]
	LastModified,
	[global::__DynamicallyInvokable]
	Accept,
	[global::__DynamicallyInvokable]
	AcceptCharset,
	[global::__DynamicallyInvokable]
	AcceptEncoding,
	[global::__DynamicallyInvokable]
	AcceptLanguage,
	[global::__DynamicallyInvokable]
	Authorization,
	[global::__DynamicallyInvokable]
	Cookie,
	[global::__DynamicallyInvokable]
	Expect,
	[global::__DynamicallyInvokable]
	From,
	[global::__DynamicallyInvokable]
	Host,
	[global::__DynamicallyInvokable]
	IfMatch,
	[global::__DynamicallyInvokable]
	IfModifiedSince,
	[global::__DynamicallyInvokable]
	IfNoneMatch,
	[global::__DynamicallyInvokable]
	IfRange,
	[global::__DynamicallyInvokable]
	IfUnmodifiedSince,
	[global::__DynamicallyInvokable]
	MaxForwards,
	[global::__DynamicallyInvokable]
	ProxyAuthorization,
	[global::__DynamicallyInvokable]
	Referer,
	[global::__DynamicallyInvokable]
	Range,
	[global::__DynamicallyInvokable]
	Te,
	[global::__DynamicallyInvokable]
	Translate,
	[global::__DynamicallyInvokable]
	UserAgent
}
