using System;
using System.Runtime.CompilerServices;
using UnrealEngine.Runtime;

namespace UnrealEngine.Engine;

[UDelegate]
[UMetaPath("/Script/Engine.ComponentEndOverlapSignature__DelegateSignature")]
public class FComponentEndOverlapSignature : FMulticastDelegate<FComponentEndOverlapSignature.Signature>
{
	public delegate void Signature(UPrimitiveComponent OverlappedComponent, AActor OtherActor, UPrimitiveComponent OtherComp, int OtherBodyIndex);

	private static bool ComponentEndOverlapSignature__DelegateSignature_IsValid;

	private static IntPtr ComponentEndOverlapSignature__DelegateSignature_FunctionAddress;

	private static int ComponentEndOverlapSignature__DelegateSignature_ParamsSize;

	private static bool ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_IsValid;

	private static FFieldAddress ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_PropertyAddress;

	private static int ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_Offset;

	private static bool ComponentEndOverlapSignature__DelegateSignature_OtherActor_IsValid;

	private static FFieldAddress ComponentEndOverlapSignature__DelegateSignature_OtherActor_PropertyAddress;

	private static int ComponentEndOverlapSignature__DelegateSignature_OtherActor_Offset;

	private static bool ComponentEndOverlapSignature__DelegateSignature_OtherComp_IsValid;

	private static FFieldAddress ComponentEndOverlapSignature__DelegateSignature_OtherComp_PropertyAddress;

	private static int ComponentEndOverlapSignature__DelegateSignature_OtherComp_Offset;

	private static bool ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_IsValid;

	private static FFieldAddress ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_PropertyAddress;

	private static int ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_Offset;

	public override Signature GetInvoker()
	{
		return Invoker;
	}

	static FComponentEndOverlapSignature()
	{
		LoadNativeType();
	}

	private static void LoadNativeType()
	{
		ComponentEndOverlapSignature__DelegateSignature_FunctionAddress = NativeReflection.GetFunction("/Script/Engine.ComponentEndOverlapSignature__DelegateSignature");
		ComponentEndOverlapSignature__DelegateSignature_ParamsSize = NativeReflection.GetFunctionParamsSize(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress);
		NativeReflectionCached.GetPropertyRef(ref ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_PropertyAddress, ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OverlappedComponent");
		ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_Offset = NativeReflectionCached.GetPropertyOffset(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OverlappedComponent");
		ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OverlappedComponent", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentEndOverlapSignature__DelegateSignature_OtherActor_PropertyAddress, ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherActor");
		ComponentEndOverlapSignature__DelegateSignature_OtherActor_Offset = NativeReflectionCached.GetPropertyOffset(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherActor");
		ComponentEndOverlapSignature__DelegateSignature_OtherActor_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherActor", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentEndOverlapSignature__DelegateSignature_OtherComp_PropertyAddress, ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherComp");
		ComponentEndOverlapSignature__DelegateSignature_OtherComp_Offset = NativeReflectionCached.GetPropertyOffset(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherComp");
		ComponentEndOverlapSignature__DelegateSignature_OtherComp_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherComp", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_PropertyAddress, ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherBodyIndex");
		ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_Offset = NativeReflectionCached.GetPropertyOffset(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherBodyIndex");
		ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentEndOverlapSignature__DelegateSignature_FunctionAddress, "OtherBodyIndex", Classes.FIntProperty);
		ComponentEndOverlapSignature__DelegateSignature_IsValid = ComponentEndOverlapSignature__DelegateSignature_FunctionAddress != IntPtr.Zero && ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_IsValid && ComponentEndOverlapSignature__DelegateSignature_OtherActor_IsValid && ComponentEndOverlapSignature__DelegateSignature_OtherComp_IsValid && ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_IsValid;
		NativeReflection.LogFunctionIsValid("/Script/Engine.ComponentEndOverlapSignature__DelegateSignature", ComponentEndOverlapSignature__DelegateSignature_IsValid);
	}

	private unsafe void Invoker(UPrimitiveComponent OverlappedComponent, AActor OtherActor, UPrimitiveComponent OtherComp, int OtherBodyIndex)
	{
		if (!ComponentEndOverlapSignature__DelegateSignature_IsValid)
		{
			NativeReflection.LogInvalidFunctionAccessed("/Script/Engine.ComponentEndOverlapSignature__DelegateSignature");
		}
		else if (IsBound)
		{
			byte* ptr = stackalloc byte[(int)(uint)(ComponentEndOverlapSignature__DelegateSignature_ParamsSize + 16)];
			int num = (int)((16L - (long)ptr) & 0xF);
			byte* ptr2 = ptr + num;
			Unsafe.InitBlockUnaligned(ptr2, 0, (uint)ComponentEndOverlapSignature__DelegateSignature_ParamsSize);
			IntPtr intPtr = new IntPtr(ptr2);
			UObjectMarshaler<UPrimitiveComponent>.ToNative(IntPtr.Add(intPtr, ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_Offset), 0, ComponentEndOverlapSignature__DelegateSignature_OverlappedComponent_PropertyAddress.Address, OverlappedComponent);
			UObjectMarshaler<AActor>.ToNative(IntPtr.Add(intPtr, ComponentEndOverlapSignature__DelegateSignature_OtherActor_Offset), 0, ComponentEndOverlapSignature__DelegateSignature_OtherActor_PropertyAddress.Address, OtherActor);
			UObjectMarshaler<UPrimitiveComponent>.ToNative(IntPtr.Add(intPtr, ComponentEndOverlapSignature__DelegateSignature_OtherComp_Offset), 0, ComponentEndOverlapSignature__DelegateSignature_OtherComp_PropertyAddress.Address, OtherComp);
			BlittableTypeMarshaler<int>.ToNative(IntPtr.Add(intPtr, ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_Offset), 0, ComponentEndOverlapSignature__DelegateSignature_OtherBodyIndex_PropertyAddress.Address, OtherBodyIndex);
			ProcessDelegate(intPtr);
		}
	}
}
