using System;
using System.Runtime.CompilerServices;
using UnrealEngine.Runtime;

namespace UnrealEngine.Engine;

[UDelegate]
[UMetaPath("/Script/Engine.ComponentBeginOverlapSignature__DelegateSignature")]
public class FComponentBeginOverlapSignature : FMulticastDelegate<FComponentBeginOverlapSignature.Signature>
{
	public delegate void Signature(UPrimitiveComponent OverlappedComponent, AActor OtherActor, UPrimitiveComponent OtherComp, int OtherBodyIndex, bool bFromSweep, FHitResult SweepResult);

	private static bool ComponentBeginOverlapSignature__DelegateSignature_IsValid;

	private static IntPtr ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress;

	private static int ComponentBeginOverlapSignature__DelegateSignature_ParamsSize;

	private static bool ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_IsValid;

	private static FFieldAddress ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_PropertyAddress;

	private static int ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_Offset;

	private static bool ComponentBeginOverlapSignature__DelegateSignature_OtherActor_IsValid;

	private static FFieldAddress ComponentBeginOverlapSignature__DelegateSignature_OtherActor_PropertyAddress;

	private static int ComponentBeginOverlapSignature__DelegateSignature_OtherActor_Offset;

	private static bool ComponentBeginOverlapSignature__DelegateSignature_OtherComp_IsValid;

	private static FFieldAddress ComponentBeginOverlapSignature__DelegateSignature_OtherComp_PropertyAddress;

	private static int ComponentBeginOverlapSignature__DelegateSignature_OtherComp_Offset;

	private static bool ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_IsValid;

	private static FFieldAddress ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_PropertyAddress;

	private static int ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_Offset;

	private static bool ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_IsValid;

	private static FFieldAddress ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_PropertyAddress;

	private static int ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_Offset;

	private static bool ComponentBeginOverlapSignature__DelegateSignature_SweepResult_IsValid;

	private static FFieldAddress ComponentBeginOverlapSignature__DelegateSignature_SweepResult_PropertyAddress;

	private static int ComponentBeginOverlapSignature__DelegateSignature_SweepResult_Offset;

	public override Signature GetInvoker()
	{
		return Invoker;
	}

	static FComponentBeginOverlapSignature()
	{
		LoadNativeType();
	}

	private static void LoadNativeType()
	{
		ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress = NativeReflection.GetFunction("/Script/Engine.ComponentBeginOverlapSignature__DelegateSignature");
		ComponentBeginOverlapSignature__DelegateSignature_ParamsSize = NativeReflection.GetFunctionParamsSize(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress);
		NativeReflectionCached.GetPropertyRef(ref ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_PropertyAddress, ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OverlappedComponent");
		ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_Offset = NativeReflectionCached.GetPropertyOffset(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OverlappedComponent");
		ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OverlappedComponent", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentBeginOverlapSignature__DelegateSignature_OtherActor_PropertyAddress, ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherActor");
		ComponentBeginOverlapSignature__DelegateSignature_OtherActor_Offset = NativeReflectionCached.GetPropertyOffset(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherActor");
		ComponentBeginOverlapSignature__DelegateSignature_OtherActor_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherActor", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentBeginOverlapSignature__DelegateSignature_OtherComp_PropertyAddress, ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherComp");
		ComponentBeginOverlapSignature__DelegateSignature_OtherComp_Offset = NativeReflectionCached.GetPropertyOffset(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherComp");
		ComponentBeginOverlapSignature__DelegateSignature_OtherComp_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherComp", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_PropertyAddress, ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherBodyIndex");
		ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_Offset = NativeReflectionCached.GetPropertyOffset(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherBodyIndex");
		ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "OtherBodyIndex", Classes.FIntProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_PropertyAddress, ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "bFromSweep");
		ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_Offset = NativeReflectionCached.GetPropertyOffset(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "bFromSweep");
		ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "bFromSweep", Classes.FBoolProperty);
		NativeReflectionCached.GetPropertyRef(ref ComponentBeginOverlapSignature__DelegateSignature_SweepResult_PropertyAddress, ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "SweepResult");
		ComponentBeginOverlapSignature__DelegateSignature_SweepResult_Offset = NativeReflectionCached.GetPropertyOffset(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "SweepResult");
		ComponentBeginOverlapSignature__DelegateSignature_SweepResult_IsValid = NativeReflectionCached.ValidatePropertyClass(ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress, "SweepResult", Classes.FStructProperty);
		ComponentBeginOverlapSignature__DelegateSignature_IsValid = ComponentBeginOverlapSignature__DelegateSignature_FunctionAddress != IntPtr.Zero && ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_IsValid && ComponentBeginOverlapSignature__DelegateSignature_OtherActor_IsValid && ComponentBeginOverlapSignature__DelegateSignature_OtherComp_IsValid && ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_IsValid && ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_IsValid && ComponentBeginOverlapSignature__DelegateSignature_SweepResult_IsValid;
		NativeReflection.LogFunctionIsValid("/Script/Engine.ComponentBeginOverlapSignature__DelegateSignature", ComponentBeginOverlapSignature__DelegateSignature_IsValid);
	}

	private unsafe void Invoker(UPrimitiveComponent OverlappedComponent, AActor OtherActor, UPrimitiveComponent OtherComp, int OtherBodyIndex, bool bFromSweep, FHitResult SweepResult)
	{
		if (!ComponentBeginOverlapSignature__DelegateSignature_IsValid)
		{
			NativeReflection.LogInvalidFunctionAccessed("/Script/Engine.ComponentBeginOverlapSignature__DelegateSignature");
		}
		else if (IsBound)
		{
			byte* ptr = stackalloc byte[(int)(uint)(ComponentBeginOverlapSignature__DelegateSignature_ParamsSize + 16)];
			int num = (int)((16L - (long)ptr) & 0xF);
			byte* ptr2 = ptr + num;
			Unsafe.InitBlockUnaligned(ptr2, 0, (uint)ComponentBeginOverlapSignature__DelegateSignature_ParamsSize);
			IntPtr intPtr = new IntPtr(ptr2);
			UObjectMarshaler<UPrimitiveComponent>.ToNative(IntPtr.Add(intPtr, ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_Offset), 0, ComponentBeginOverlapSignature__DelegateSignature_OverlappedComponent_PropertyAddress.Address, OverlappedComponent);
			UObjectMarshaler<AActor>.ToNative(IntPtr.Add(intPtr, ComponentBeginOverlapSignature__DelegateSignature_OtherActor_Offset), 0, ComponentBeginOverlapSignature__DelegateSignature_OtherActor_PropertyAddress.Address, OtherActor);
			UObjectMarshaler<UPrimitiveComponent>.ToNative(IntPtr.Add(intPtr, ComponentBeginOverlapSignature__DelegateSignature_OtherComp_Offset), 0, ComponentBeginOverlapSignature__DelegateSignature_OtherComp_PropertyAddress.Address, OtherComp);
			BlittableTypeMarshaler<int>.ToNative(IntPtr.Add(intPtr, ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_Offset), 0, ComponentBeginOverlapSignature__DelegateSignature_OtherBodyIndex_PropertyAddress.Address, OtherBodyIndex);
			BoolMarshaler.ToNative(IntPtr.Add(intPtr, ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_Offset), 0, ComponentBeginOverlapSignature__DelegateSignature_bFromSweep_PropertyAddress.Address, bFromSweep);
			NativeReflection.InitializeValue_InContainer(ComponentBeginOverlapSignature__DelegateSignature_SweepResult_PropertyAddress.Address, intPtr);
			FHitResult.ToNative(IntPtr.Add(intPtr, ComponentBeginOverlapSignature__DelegateSignature_SweepResult_Offset), 0, ComponentBeginOverlapSignature__DelegateSignature_SweepResult_PropertyAddress.Address, SweepResult);
			ProcessDelegate(intPtr);
		}
	}
}
