using System;
using System.Runtime.CompilerServices;
using UnrealEngine.Runtime;

namespace UnrealEngine.Engine;

[UDelegate]
[UMetaPath("/Script/Engine.TakeRadialDamageSignature__DelegateSignature")]
public class FTakeRadialDamageSignature : FMulticastDelegate<FTakeRadialDamageSignature.Signature>
{
	public delegate void Signature(AActor DamagedActor, float Damage, UDamageType DamageType, FVector Origin, FHitResult HitInfo, AController InstigatedBy, AActor DamageCauser);

	private static bool TakeRadialDamageSignature__DelegateSignature_IsValid;

	private static IntPtr TakeRadialDamageSignature__DelegateSignature_FunctionAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_ParamsSize;

	private static bool TakeRadialDamageSignature__DelegateSignature_DamagedActor_IsValid;

	private static FFieldAddress TakeRadialDamageSignature__DelegateSignature_DamagedActor_PropertyAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_DamagedActor_Offset;

	private static bool TakeRadialDamageSignature__DelegateSignature_Damage_IsValid;

	private static FFieldAddress TakeRadialDamageSignature__DelegateSignature_Damage_PropertyAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_Damage_Offset;

	private static bool TakeRadialDamageSignature__DelegateSignature_DamageType_IsValid;

	private static FFieldAddress TakeRadialDamageSignature__DelegateSignature_DamageType_PropertyAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_DamageType_Offset;

	private static bool TakeRadialDamageSignature__DelegateSignature_Origin_IsValid;

	private static FFieldAddress TakeRadialDamageSignature__DelegateSignature_Origin_PropertyAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_Origin_Offset;

	private static bool TakeRadialDamageSignature__DelegateSignature_HitInfo_IsValid;

	private static FFieldAddress TakeRadialDamageSignature__DelegateSignature_HitInfo_PropertyAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_HitInfo_Offset;

	private static bool TakeRadialDamageSignature__DelegateSignature_InstigatedBy_IsValid;

	private static FFieldAddress TakeRadialDamageSignature__DelegateSignature_InstigatedBy_PropertyAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_InstigatedBy_Offset;

	private static bool TakeRadialDamageSignature__DelegateSignature_DamageCauser_IsValid;

	private static FFieldAddress TakeRadialDamageSignature__DelegateSignature_DamageCauser_PropertyAddress;

	private static int TakeRadialDamageSignature__DelegateSignature_DamageCauser_Offset;

	public override Signature GetInvoker()
	{
		return Invoker;
	}

	static FTakeRadialDamageSignature()
	{
		LoadNativeType();
	}

	private static void LoadNativeType()
	{
		TakeRadialDamageSignature__DelegateSignature_FunctionAddress = NativeReflection.GetFunction("/Script/Engine.TakeRadialDamageSignature__DelegateSignature");
		TakeRadialDamageSignature__DelegateSignature_ParamsSize = NativeReflection.GetFunctionParamsSize(TakeRadialDamageSignature__DelegateSignature_FunctionAddress);
		NativeReflectionCached.GetPropertyRef(ref TakeRadialDamageSignature__DelegateSignature_DamagedActor_PropertyAddress, TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamagedActor");
		TakeRadialDamageSignature__DelegateSignature_DamagedActor_Offset = NativeReflectionCached.GetPropertyOffset(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamagedActor");
		TakeRadialDamageSignature__DelegateSignature_DamagedActor_IsValid = NativeReflectionCached.ValidatePropertyClass(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamagedActor", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref TakeRadialDamageSignature__DelegateSignature_Damage_PropertyAddress, TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "Damage");
		TakeRadialDamageSignature__DelegateSignature_Damage_Offset = NativeReflectionCached.GetPropertyOffset(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "Damage");
		TakeRadialDamageSignature__DelegateSignature_Damage_IsValid = NativeReflectionCached.ValidatePropertyClass(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "Damage", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref TakeRadialDamageSignature__DelegateSignature_DamageType_PropertyAddress, TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamageType");
		TakeRadialDamageSignature__DelegateSignature_DamageType_Offset = NativeReflectionCached.GetPropertyOffset(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamageType");
		TakeRadialDamageSignature__DelegateSignature_DamageType_IsValid = NativeReflectionCached.ValidatePropertyClass(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamageType", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref TakeRadialDamageSignature__DelegateSignature_Origin_PropertyAddress, TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "Origin");
		TakeRadialDamageSignature__DelegateSignature_Origin_Offset = NativeReflectionCached.GetPropertyOffset(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "Origin");
		TakeRadialDamageSignature__DelegateSignature_Origin_IsValid = NativeReflectionCached.ValidatePropertyClass(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "Origin", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref TakeRadialDamageSignature__DelegateSignature_HitInfo_PropertyAddress, TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "HitInfo");
		TakeRadialDamageSignature__DelegateSignature_HitInfo_Offset = NativeReflectionCached.GetPropertyOffset(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "HitInfo");
		TakeRadialDamageSignature__DelegateSignature_HitInfo_IsValid = NativeReflectionCached.ValidatePropertyClass(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "HitInfo", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref TakeRadialDamageSignature__DelegateSignature_InstigatedBy_PropertyAddress, TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "InstigatedBy");
		TakeRadialDamageSignature__DelegateSignature_InstigatedBy_Offset = NativeReflectionCached.GetPropertyOffset(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "InstigatedBy");
		TakeRadialDamageSignature__DelegateSignature_InstigatedBy_IsValid = NativeReflectionCached.ValidatePropertyClass(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "InstigatedBy", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref TakeRadialDamageSignature__DelegateSignature_DamageCauser_PropertyAddress, TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamageCauser");
		TakeRadialDamageSignature__DelegateSignature_DamageCauser_Offset = NativeReflectionCached.GetPropertyOffset(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamageCauser");
		TakeRadialDamageSignature__DelegateSignature_DamageCauser_IsValid = NativeReflectionCached.ValidatePropertyClass(TakeRadialDamageSignature__DelegateSignature_FunctionAddress, "DamageCauser", Classes.FObjectProperty);
		TakeRadialDamageSignature__DelegateSignature_IsValid = TakeRadialDamageSignature__DelegateSignature_FunctionAddress != IntPtr.Zero && TakeRadialDamageSignature__DelegateSignature_DamagedActor_IsValid && TakeRadialDamageSignature__DelegateSignature_Damage_IsValid && TakeRadialDamageSignature__DelegateSignature_DamageType_IsValid && TakeRadialDamageSignature__DelegateSignature_Origin_IsValid && TakeRadialDamageSignature__DelegateSignature_HitInfo_IsValid && TakeRadialDamageSignature__DelegateSignature_InstigatedBy_IsValid && TakeRadialDamageSignature__DelegateSignature_DamageCauser_IsValid;
		NativeReflection.LogFunctionIsValid("/Script/Engine.TakeRadialDamageSignature__DelegateSignature", TakeRadialDamageSignature__DelegateSignature_IsValid);
	}

	private unsafe void Invoker(AActor DamagedActor, float Damage, UDamageType DamageType, FVector Origin, FHitResult HitInfo, AController InstigatedBy, AActor DamageCauser)
	{
		if (!TakeRadialDamageSignature__DelegateSignature_IsValid)
		{
			NativeReflection.LogInvalidFunctionAccessed("/Script/Engine.TakeRadialDamageSignature__DelegateSignature");
		}
		else if (IsBound)
		{
			byte* ptr = stackalloc byte[(int)(uint)(TakeRadialDamageSignature__DelegateSignature_ParamsSize + 16)];
			int num = (int)((16L - (long)ptr) & 0xF);
			byte* ptr2 = ptr + num;
			Unsafe.InitBlockUnaligned(ptr2, 0, (uint)TakeRadialDamageSignature__DelegateSignature_ParamsSize);
			IntPtr intPtr = new IntPtr(ptr2);
			UObjectMarshaler<AActor>.ToNative(IntPtr.Add(intPtr, TakeRadialDamageSignature__DelegateSignature_DamagedActor_Offset), 0, TakeRadialDamageSignature__DelegateSignature_DamagedActor_PropertyAddress.Address, DamagedActor);
			BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, TakeRadialDamageSignature__DelegateSignature_Damage_Offset), 0, TakeRadialDamageSignature__DelegateSignature_Damage_PropertyAddress.Address, Damage);
			UObjectMarshaler<UDamageType>.ToNative(IntPtr.Add(intPtr, TakeRadialDamageSignature__DelegateSignature_DamageType_Offset), 0, TakeRadialDamageSignature__DelegateSignature_DamageType_PropertyAddress.Address, DamageType);
			BlittableTypeMarshaler<FVector>.ToNative(IntPtr.Add(intPtr, TakeRadialDamageSignature__DelegateSignature_Origin_Offset), 0, TakeRadialDamageSignature__DelegateSignature_Origin_PropertyAddress.Address, Origin);
			NativeReflection.InitializeValue_InContainer(TakeRadialDamageSignature__DelegateSignature_HitInfo_PropertyAddress.Address, intPtr);
			FHitResult.ToNative(IntPtr.Add(intPtr, TakeRadialDamageSignature__DelegateSignature_HitInfo_Offset), 0, TakeRadialDamageSignature__DelegateSignature_HitInfo_PropertyAddress.Address, HitInfo);
			UObjectMarshaler<AController>.ToNative(IntPtr.Add(intPtr, TakeRadialDamageSignature__DelegateSignature_InstigatedBy_Offset), 0, TakeRadialDamageSignature__DelegateSignature_InstigatedBy_PropertyAddress.Address, InstigatedBy);
			UObjectMarshaler<AActor>.ToNative(IntPtr.Add(intPtr, TakeRadialDamageSignature__DelegateSignature_DamageCauser_Offset), 0, TakeRadialDamageSignature__DelegateSignature_DamageCauser_PropertyAddress.Address, DamageCauser);
			ProcessDelegate(intPtr);
		}
	}
}
