using System;
using System.Runtime.CompilerServices;
using UnrealEngine.Engine;
using UnrealEngine.Runtime;

namespace UnrealEngine.Foliage;

[UDelegate]
[UMetaPath("/Script/Foliage.InstancePointDamageSignature__DelegateSignature")]
public class FInstancePointDamageSignature : FMulticastDelegate<FInstancePointDamageSignature.Signature>
{
	public delegate void Signature(int InstanceIndex, float Damage, AController InstigatedBy, FVector HitLocation, FVector ShotFromDirection, UDamageType DamageType, AActor DamageCauser);

	private static bool InstancePointDamageSignature__DelegateSignature_IsValid;

	private static IntPtr InstancePointDamageSignature__DelegateSignature_FunctionAddress;

	private static int InstancePointDamageSignature__DelegateSignature_ParamsSize;

	private static bool InstancePointDamageSignature__DelegateSignature_InstanceIndex_IsValid;

	private static FFieldAddress InstancePointDamageSignature__DelegateSignature_InstanceIndex_PropertyAddress;

	private static int InstancePointDamageSignature__DelegateSignature_InstanceIndex_Offset;

	private static bool InstancePointDamageSignature__DelegateSignature_Damage_IsValid;

	private static FFieldAddress InstancePointDamageSignature__DelegateSignature_Damage_PropertyAddress;

	private static int InstancePointDamageSignature__DelegateSignature_Damage_Offset;

	private static bool InstancePointDamageSignature__DelegateSignature_InstigatedBy_IsValid;

	private static FFieldAddress InstancePointDamageSignature__DelegateSignature_InstigatedBy_PropertyAddress;

	private static int InstancePointDamageSignature__DelegateSignature_InstigatedBy_Offset;

	private static bool InstancePointDamageSignature__DelegateSignature_HitLocation_IsValid;

	private static FFieldAddress InstancePointDamageSignature__DelegateSignature_HitLocation_PropertyAddress;

	private static int InstancePointDamageSignature__DelegateSignature_HitLocation_Offset;

	private static bool InstancePointDamageSignature__DelegateSignature_ShotFromDirection_IsValid;

	private static FFieldAddress InstancePointDamageSignature__DelegateSignature_ShotFromDirection_PropertyAddress;

	private static int InstancePointDamageSignature__DelegateSignature_ShotFromDirection_Offset;

	private static bool InstancePointDamageSignature__DelegateSignature_DamageType_IsValid;

	private static FFieldAddress InstancePointDamageSignature__DelegateSignature_DamageType_PropertyAddress;

	private static int InstancePointDamageSignature__DelegateSignature_DamageType_Offset;

	private static bool InstancePointDamageSignature__DelegateSignature_DamageCauser_IsValid;

	private static FFieldAddress InstancePointDamageSignature__DelegateSignature_DamageCauser_PropertyAddress;

	private static int InstancePointDamageSignature__DelegateSignature_DamageCauser_Offset;

	public override Signature GetInvoker()
	{
		return Invoker;
	}

	static FInstancePointDamageSignature()
	{
		LoadNativeType();
	}

	private static void LoadNativeType()
	{
		InstancePointDamageSignature__DelegateSignature_FunctionAddress = NativeReflection.GetFunction("/Script/Foliage.InstancePointDamageSignature__DelegateSignature");
		InstancePointDamageSignature__DelegateSignature_ParamsSize = NativeReflection.GetFunctionParamsSize(InstancePointDamageSignature__DelegateSignature_FunctionAddress);
		NativeReflectionCached.GetPropertyRef(ref InstancePointDamageSignature__DelegateSignature_InstanceIndex_PropertyAddress, InstancePointDamageSignature__DelegateSignature_FunctionAddress, "InstanceIndex");
		InstancePointDamageSignature__DelegateSignature_InstanceIndex_Offset = NativeReflectionCached.GetPropertyOffset(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "InstanceIndex");
		InstancePointDamageSignature__DelegateSignature_InstanceIndex_IsValid = NativeReflectionCached.ValidatePropertyClass(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "InstanceIndex", Classes.FIntProperty);
		NativeReflectionCached.GetPropertyRef(ref InstancePointDamageSignature__DelegateSignature_Damage_PropertyAddress, InstancePointDamageSignature__DelegateSignature_FunctionAddress, "Damage");
		InstancePointDamageSignature__DelegateSignature_Damage_Offset = NativeReflectionCached.GetPropertyOffset(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "Damage");
		InstancePointDamageSignature__DelegateSignature_Damage_IsValid = NativeReflectionCached.ValidatePropertyClass(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "Damage", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref InstancePointDamageSignature__DelegateSignature_InstigatedBy_PropertyAddress, InstancePointDamageSignature__DelegateSignature_FunctionAddress, "InstigatedBy");
		InstancePointDamageSignature__DelegateSignature_InstigatedBy_Offset = NativeReflectionCached.GetPropertyOffset(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "InstigatedBy");
		InstancePointDamageSignature__DelegateSignature_InstigatedBy_IsValid = NativeReflectionCached.ValidatePropertyClass(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "InstigatedBy", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref InstancePointDamageSignature__DelegateSignature_HitLocation_PropertyAddress, InstancePointDamageSignature__DelegateSignature_FunctionAddress, "HitLocation");
		InstancePointDamageSignature__DelegateSignature_HitLocation_Offset = NativeReflectionCached.GetPropertyOffset(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "HitLocation");
		InstancePointDamageSignature__DelegateSignature_HitLocation_IsValid = NativeReflectionCached.ValidatePropertyClass(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "HitLocation", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref InstancePointDamageSignature__DelegateSignature_ShotFromDirection_PropertyAddress, InstancePointDamageSignature__DelegateSignature_FunctionAddress, "ShotFromDirection");
		InstancePointDamageSignature__DelegateSignature_ShotFromDirection_Offset = NativeReflectionCached.GetPropertyOffset(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "ShotFromDirection");
		InstancePointDamageSignature__DelegateSignature_ShotFromDirection_IsValid = NativeReflectionCached.ValidatePropertyClass(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "ShotFromDirection", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref InstancePointDamageSignature__DelegateSignature_DamageType_PropertyAddress, InstancePointDamageSignature__DelegateSignature_FunctionAddress, "DamageType");
		InstancePointDamageSignature__DelegateSignature_DamageType_Offset = NativeReflectionCached.GetPropertyOffset(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "DamageType");
		InstancePointDamageSignature__DelegateSignature_DamageType_IsValid = NativeReflectionCached.ValidatePropertyClass(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "DamageType", Classes.FObjectProperty);
		NativeReflectionCached.GetPropertyRef(ref InstancePointDamageSignature__DelegateSignature_DamageCauser_PropertyAddress, InstancePointDamageSignature__DelegateSignature_FunctionAddress, "DamageCauser");
		InstancePointDamageSignature__DelegateSignature_DamageCauser_Offset = NativeReflectionCached.GetPropertyOffset(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "DamageCauser");
		InstancePointDamageSignature__DelegateSignature_DamageCauser_IsValid = NativeReflectionCached.ValidatePropertyClass(InstancePointDamageSignature__DelegateSignature_FunctionAddress, "DamageCauser", Classes.FObjectProperty);
		InstancePointDamageSignature__DelegateSignature_IsValid = InstancePointDamageSignature__DelegateSignature_FunctionAddress != IntPtr.Zero && InstancePointDamageSignature__DelegateSignature_InstanceIndex_IsValid && InstancePointDamageSignature__DelegateSignature_Damage_IsValid && InstancePointDamageSignature__DelegateSignature_InstigatedBy_IsValid && InstancePointDamageSignature__DelegateSignature_HitLocation_IsValid && InstancePointDamageSignature__DelegateSignature_ShotFromDirection_IsValid && InstancePointDamageSignature__DelegateSignature_DamageType_IsValid && InstancePointDamageSignature__DelegateSignature_DamageCauser_IsValid;
		NativeReflection.LogFunctionIsValid("/Script/Foliage.InstancePointDamageSignature__DelegateSignature", InstancePointDamageSignature__DelegateSignature_IsValid);
	}

	private unsafe void Invoker(int InstanceIndex, float Damage, AController InstigatedBy, FVector HitLocation, FVector ShotFromDirection, UDamageType DamageType, AActor DamageCauser)
	{
		if (!InstancePointDamageSignature__DelegateSignature_IsValid)
		{
			NativeReflection.LogInvalidFunctionAccessed("/Script/Foliage.InstancePointDamageSignature__DelegateSignature");
		}
		else if (IsBound)
		{
			byte* ptr = stackalloc byte[(int)(uint)(InstancePointDamageSignature__DelegateSignature_ParamsSize + 16)];
			int num = (int)((16L - (long)ptr) & 0xF);
			byte* ptr2 = ptr + num;
			Unsafe.InitBlockUnaligned(ptr2, 0, (uint)InstancePointDamageSignature__DelegateSignature_ParamsSize);
			IntPtr intPtr = new IntPtr(ptr2);
			BlittableTypeMarshaler<int>.ToNative(IntPtr.Add(intPtr, InstancePointDamageSignature__DelegateSignature_InstanceIndex_Offset), 0, InstancePointDamageSignature__DelegateSignature_InstanceIndex_PropertyAddress.Address, InstanceIndex);
			BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, InstancePointDamageSignature__DelegateSignature_Damage_Offset), 0, InstancePointDamageSignature__DelegateSignature_Damage_PropertyAddress.Address, Damage);
			UObjectMarshaler<AController>.ToNative(IntPtr.Add(intPtr, InstancePointDamageSignature__DelegateSignature_InstigatedBy_Offset), 0, InstancePointDamageSignature__DelegateSignature_InstigatedBy_PropertyAddress.Address, InstigatedBy);
			BlittableTypeMarshaler<FVector>.ToNative(IntPtr.Add(intPtr, InstancePointDamageSignature__DelegateSignature_HitLocation_Offset), 0, InstancePointDamageSignature__DelegateSignature_HitLocation_PropertyAddress.Address, HitLocation);
			BlittableTypeMarshaler<FVector>.ToNative(IntPtr.Add(intPtr, InstancePointDamageSignature__DelegateSignature_ShotFromDirection_Offset), 0, InstancePointDamageSignature__DelegateSignature_ShotFromDirection_PropertyAddress.Address, ShotFromDirection);
			UObjectMarshaler<UDamageType>.ToNative(IntPtr.Add(intPtr, InstancePointDamageSignature__DelegateSignature_DamageType_Offset), 0, InstancePointDamageSignature__DelegateSignature_DamageType_PropertyAddress.Address, DamageType);
			UObjectMarshaler<AActor>.ToNative(IntPtr.Add(intPtr, InstancePointDamageSignature__DelegateSignature_DamageCauser_Offset), 0, InstancePointDamageSignature__DelegateSignature_DamageCauser_PropertyAddress.Address, DamageCauser);
			ProcessDelegate(intPtr);
		}
	}
}
