namespace System.Linq.Expressions;

[global::__DynamicallyInvokable]
public enum ExpressionType
{
	[global::__DynamicallyInvokable]
	Add,
	[global::__DynamicallyInvokable]
	AddChecked,
	[global::__DynamicallyInvokable]
	And,
	[global::__DynamicallyInvokable]
	AndAlso,
	[global::__DynamicallyInvokable]
	ArrayLength,
	[global::__DynamicallyInvokable]
	ArrayIndex,
	[global::__DynamicallyInvokable]
	Call,
	[global::__DynamicallyInvokable]
	Coalesce,
	[global::__DynamicallyInvokable]
	Conditional,
	[global::__DynamicallyInvokable]
	Constant,
	[global::__DynamicallyInvokable]
	Convert,
	[global::__DynamicallyInvokable]
	ConvertChecked,
	[global::__DynamicallyInvokable]
	Divide,
	[global::__DynamicallyInvokable]
	Equal,
	[global::__DynamicallyInvokable]
	ExclusiveOr,
	[global::__DynamicallyInvokable]
	GreaterThan,
	[global::__DynamicallyInvokable]
	GreaterThanOrEqual,
	[global::__DynamicallyInvokable]
	Invoke,
	[global::__DynamicallyInvokable]
	Lambda,
	[global::__DynamicallyInvokable]
	LeftShift,
	[global::__DynamicallyInvokable]
	LessThan,
	[global::__DynamicallyInvokable]
	LessThanOrEqual,
	[global::__DynamicallyInvokable]
	ListInit,
	[global::__DynamicallyInvokable]
	MemberAccess,
	[global::__DynamicallyInvokable]
	MemberInit,
	[global::__DynamicallyInvokable]
	Modulo,
	[global::__DynamicallyInvokable]
	Multiply,
	[global::__DynamicallyInvokable]
	MultiplyChecked,
	[global::__DynamicallyInvokable]
	Negate,
	[global::__DynamicallyInvokable]
	UnaryPlus,
	[global::__DynamicallyInvokable]
	NegateChecked,
	[global::__DynamicallyInvokable]
	New,
	[global::__DynamicallyInvokable]
	NewArrayInit,
	[global::__DynamicallyInvokable]
	NewArrayBounds,
	[global::__DynamicallyInvokable]
	Not,
	[global::__DynamicallyInvokable]
	NotEqual,
	[global::__DynamicallyInvokable]
	Or,
	[global::__DynamicallyInvokable]
	OrElse,
	[global::__DynamicallyInvokable]
	Parameter,
	[global::__DynamicallyInvokable]
	Power,
	[global::__DynamicallyInvokable]
	Quote,
	[global::__DynamicallyInvokable]
	RightShift,
	[global::__DynamicallyInvokable]
	Subtract,
	[global::__DynamicallyInvokable]
	SubtractChecked,
	[global::__DynamicallyInvokable]
	TypeAs,
	[global::__DynamicallyInvokable]
	TypeIs,
	[global::__DynamicallyInvokable]
	Assign,
	[global::__DynamicallyInvokable]
	Block,
	[global::__DynamicallyInvokable]
	DebugInfo,
	[global::__DynamicallyInvokable]
	Decrement,
	[global::__DynamicallyInvokable]
	Dynamic,
	[global::__DynamicallyInvokable]
	Default,
	[global::__DynamicallyInvokable]
	Extension,
	[global::__DynamicallyInvokable]
	Goto,
	[global::__DynamicallyInvokable]
	Increment,
	[global::__DynamicallyInvokable]
	Index,
	[global::__DynamicallyInvokable]
	Label,
	[global::__DynamicallyInvokable]
	RuntimeVariables,
	[global::__DynamicallyInvokable]
	Loop,
	[global::__DynamicallyInvokable]
	Switch,
	[global::__DynamicallyInvokable]
	Throw,
	[global::__DynamicallyInvokable]
	Try,
	[global::__DynamicallyInvokable]
	Unbox,
	[global::__DynamicallyInvokable]
	AddAssign,
	[global::__DynamicallyInvokable]
	AndAssign,
	[global::__DynamicallyInvokable]
	DivideAssign,
	[global::__DynamicallyInvokable]
	ExclusiveOrAssign,
	[global::__DynamicallyInvokable]
	LeftShiftAssign,
	[global::__DynamicallyInvokable]
	ModuloAssign,
	[global::__DynamicallyInvokable]
	MultiplyAssign,
	[global::__DynamicallyInvokable]
	OrAssign,
	[global::__DynamicallyInvokable]
	PowerAssign,
	[global::__DynamicallyInvokable]
	RightShiftAssign,
	[global::__DynamicallyInvokable]
	SubtractAssign,
	[global::__DynamicallyInvokable]
	AddAssignChecked,
	[global::__DynamicallyInvokable]
	MultiplyAssignChecked,
	[global::__DynamicallyInvokable]
	SubtractAssignChecked,
	[global::__DynamicallyInvokable]
	PreIncrementAssign,
	[global::__DynamicallyInvokable]
	PreDecrementAssign,
	[global::__DynamicallyInvokable]
	PostIncrementAssign,
	[global::__DynamicallyInvokable]
	PostDecrementAssign,
	[global::__DynamicallyInvokable]
	TypeEqual,
	[global::__DynamicallyInvokable]
	OnesComplement,
	[global::__DynamicallyInvokable]
	IsTrue,
	[global::__DynamicallyInvokable]
	IsFalse
}
