using UnrealEngine.Runtime;

namespace b1.Plugins.GSEHoudini;

[UEnum]
[UMetaPath("/Script/GSEHoudini.EGSHPropertyType", "GSEHoudini", UnrealModuleType.GamePlugin)]
public enum EGSHPropertyType
{
	EGSHPROPERTY_NONE,
	EGSHPROPERTY_INT,
	EGSHPROPERTY_FLOAT,
	EGSHPROPERTY_FSTRING,
	EGSHPROPERTY_FNAME,
	EGSHPROPERTY_BOOL,
	EGSHPROPERTY_OBJECT,
	EGSHPROPERTY_STRUCT,
	EGSHPROPERTY_STATICMESH,
	EGSHPROPERTY_ARRAY,
	EGSHPROPERTY_MAP,
	EGSHPROPERTY_UNKNOWN
}
