using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using AOT;
using b1.GameMode;
using b1.GSMUI.GSWidget;
using b1.Plugins.Calliope;
using b1.Plugins.DonAINavigation;
using b1.Plugins.GSAnimationKeyBlender;
using b1.Plugins.GSInput;
using b1.Plugins.MM;
using b1.UI;
using b1.UI.Comm;
using BaseU3;
using BtlB1;
using BtlShare;
using CommB1;
using CsB1;
using Google.Protobuf;
using Google.Protobuf.Collections;
using GSE.GSNet;
using GsOnline;
using Gssdk;
using ILRuntime.Runtime.Intepreter;
using LitJson;
using ResB1;
using UnrealEngine.AIModule;
using UnrealEngine.CinematicCamera;
using UnrealEngine.Engine;
using UnrealEngine.GeometryCollectionEngine;
using UnrealEngine.ImageWriteQueue;
using UnrealEngine.InputCore;
using UnrealEngine.Landscape;
using UnrealEngine.LevelSequence;
using UnrealEngine.MediaAssets;
using UnrealEngine.MovieScene;
using UnrealEngine.NavigationSystem;
using UnrealEngine.Plugins.ApexDestruction;
using UnrealEngine.Plugins.EnhancedInput;
using UnrealEngine.Plugins.GameplayCameras;
using UnrealEngine.Plugins.Niagara;
using UnrealEngine.Plugins.Paper2D;
using UnrealEngine.Plugins.ProceduralMeshComponent;
using UnrealEngine.Runtime;
using UnrealEngine.Slate;
using UnrealEngine.SlateCore;
using UnrealEngine.UMG;

namespace b1;

[UClass]
[Blueprintable]
[BlueprintType]
public class ModuleRefMain : UObject, IAssemblyRef_GSECore, IAssemblyRef_BtlSvrMain
{
	private static List<object> FakeObjs = new List<object>();

	public static void FakeIL2CPPRef()
	{
		FakeObjs.Add(new UObject());
		FakeObjs.Add(new AActor());
		FakeObjs.Add(new APawn());
		FakeObjs.Add(new AIController());
		FakeObjs.Add(new UActorComponent());
		FakeObjs.Add(new USceneComponent());
		FakeObjs.Add(new UActorComponentCS());
		FakeObjs.Add(new ACharacter());
		FakeObjs.Add(new AHUD());
		FakeObjs.Add(new AGSE_SequenceMasterCppBase());
		FakeObjs.Add(new UPrimaryDataAsset());
		FakeObjs.Add(new UPrimitiveComponent());
		FakeObjs.Add(new UUserWidget());
		FakeObjs.Add(new UBlueprintFunctionLibrary());
		FakeObjs.Add(new ADefaultPawn());
		FakeObjs.Add(new UWorld());
		FakeObjs.Add(new UStaticMeshComponent());
		FakeObjs.Add(new UPrimitiveComponent());
		FakeObjs.Add(new UParticleSystemComponent());
		FakeObjs.Add(new UParticleSystem());
		FakeObjs.Add(new UCapsuleComponent());
		FakeObjs.Add(new USphereComponent());
		FakeObjs.Add(new UBoxComponent());
		FakeObjs.Add(new USkeletalMesh());
		FakeObjs.Add(new USkeletalMeshComponent());
		FakeObjs.Add(new UCameraComponent());
		FakeObjs.Add(new USceneCaptureComponent2D());
		FakeObjs.Add(new UProjectileMovementComponent());
		FakeObjs.Add(new USpringArmComponent());
		FakeObjs.Add(new UPoseableMeshComponent());
		FakeObjs.Add(new UCurveFloat());
		FakeObjs.Add(new UTexture2D());
		FakeObjs.Add(new UMaterialInstanceDynamic());
		FakeObjs.Add(new ACameraActor());
		FakeObjs.Add(new UAnimSequence());
		FakeObjs.Add(new UAnimComposite());
		FakeObjs.Add(new UAnimMontage());
		FakeObjs.Add(new UBlendSpace());
		FakeObjs.Add(new UInputComponent());
		FakeObjs.Add(new ULevel());
		FakeObjs.Add(new ULevelStreaming());
		FakeObjs.Add(new UAimOffsetBlendSpace());
		FakeObjs.Add(new UCurveLinearColor());
		FakeObjs.Add(new UMaterialInstanceConstant());
		FakeObjs.Add(new ATriggerBase());
		FakeObjs.Add(new USplineComponent());
		FakeObjs.Add(new UChildActorComponent());
		FakeObjs.Add(new UDirectionalLightComponent());
		FakeObjs.Add(new UExponentialHeightFogComponent());
		FakeObjs.Add(new UInstancedStaticMeshComponent());
		FakeObjs.Add(new UMeshComponent());
		FakeObjs.Add(new USkyLightComponent());
		FakeObjs.Add(new UTextRenderComponent());
		FakeObjs.Add(new UPostProcessComponent());
		FakeObjs.Add(new UPointLightComponent());
		FakeObjs.Add(new UArrowComponent());
		FakeObjs.Add(new UAudioComponent());
		FakeObjs.Add(new AInfo());
		FakeObjs.Add(new APlayerCameraManager());
		FakeObjs.Add(new UBrainComponent());
		FakeObjs.Add(new UBehaviorTree());
		FakeObjs.Add(new UBehaviorTreeComponent());
		FakeObjs.Add(new UAIPerceptionComponent());
		FakeObjs.Add(new UAIPerceptionStimuliSourceComponent());
		FakeObjs.Add(new UBlackboardKeyType());
		FakeObjs.Add(new UEnvQuery());
		FakeObjs.Add(new ALandscape());
		FakeObjs.Add(new UDestructibleComponent());
		FakeObjs.Add(new ANiagaraActor());
		FakeObjs.Add(new UNiagaraComponent());
		FakeObjs.Add(new UNiagaraSystem());
		FakeObjs.Add(new UMaterial());
		FakeObjs.Add(new UBaseActorCompTickable());
		FakeObjs.Add(new UAnimationAnalyzer());
		FakeObjs.Add(new ACameraRig_Crane());
		FakeObjs.Add(new ACameraRig_Rail());
		FakeObjs.Add(new ACineCameraActor());
		FakeObjs.Add(EDescendantScrollDestination.IntoView);
		FakeObjs.Add(EUINavigationRule.Escape);
		FakeObjs.Add(new UGridPanel());
		FakeObjs.Add(new USizeBox());
		FakeObjs.Add(new UMatineeCameraShake());
		FakeObjs.Add(new Dictionary<byte, string>());
		FakeObjs.Add(new Dictionary<byte, FName>());
		FakeObjs.Add(new Dictionary<int, string>());
		FakeObjs.Add(new Dictionary<int, int>());
		FakeObjs.Add(new Dictionary<string, int>());
		FakeObjs.Add(new Dictionary<byte, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<int, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<string, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<int, List<Tuple<byte, IMessage>>>());
		FakeObjs.Add(new Dictionary<int, List<Tuple<int, IMessage>>>());
		FakeObjs.Add(new Dictionary<uint, FVector2D>());
		FakeObjs.Add(new Dictionary<int, long>());
		FakeObjs.Add(new Dictionary<uint, bool>());
		FakeObjs.Add(new Dictionary<long, int>());
		FakeObjs.Add(new Dictionary<uint, int>());
		FakeObjs.Add(new Dictionary<ulong, int>());
		FakeObjs.Add(new Dictionary<float, int>());
		FakeObjs.Add(new Dictionary<double, int>());
		FakeObjs.Add(new Dictionary<bool, int>());
		FakeObjs.Add(new Dictionary<byte, int>());
		FakeObjs.Add(new Dictionary<ILTypeInstance, int>());
		FakeObjs.Add(new Dictionary<float, FVector2D>());
		FakeObjs.Add(new Dictionary<ColorType, UWidgetAnimation>());
		FakeObjs.Add(new Dictionary<EquipPosition, UComboBoxString>());
		FakeObjs.Add(new Dictionary<FVector2D, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<Type, int>());
		FakeObjs.Add(new Dictionary<int, AActor>());
		FakeObjs.Add(new Dictionary<int, GSButtonCheck>());
		FakeObjs.Add(new Dictionary<int, Type>());
		FakeObjs.Add(new Dictionary<int, UImage>());
		FakeObjs.Add(new Dictionary<int, UWidget>());
		FakeObjs.Add(new Dictionary<int, int>());
		FakeObjs.Add(new Dictionary<string, UMaterialInstanceDynamic>());
		FakeObjs.Add(new Dictionary<uint, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<uint, ILTypeInstance>());
		FakeObjs.Add(new Tuple<int, IMessage>(0, null));
		FakeObjs.Add(new Tuple<int, ILTypeInstance>(0, null));
		FakeObjs.Add(new List<Tuple<int, IMessage>>());
		FakeObjs.Add(new List<Tuple<int, ILTypeInstance>>());
		FakeObjs.Add(new Dictionary<int, List<Tuple<int, IMessage>>>());
		FakeObjs.Add(new Dictionary<int, List<Tuple<int, ILTypeInstance>>>());
		FakeObjs.Add(new Dictionary<int, FName>());
		FakeObjs.Add(new Dictionary<UWidget, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<ulong, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<int, FVector2D>());
		FakeObjs.Add(new Dictionary<EDeadReason, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<EquipPosition, UComboBoxString>());
		FakeObjs.Add(new Dictionary<int, BUI_Button>());
		FakeObjs.Add(new Dictionary<int, FUStMovieSequenceDesc>());
		FakeObjs.Add(new Dictionary<int, Srt>());
		FakeObjs.Add(new Dictionary<int, bool>());
		FakeObjs.Add(new SortedDictionary<int, Srt>());
		FakeObjs.Add(new Tuple<GsOnline.DataSyncFlag, IMessage>(GsOnline.DataSyncFlag.SyncFlagAdd, null));
		FakeObjs.Add(new HashSet<int>());
		FakeObjs.Add(new HashSet<long>());
		FakeObjs.Add(new HashSet<uint>());
		FakeObjs.Add(new HashSet<ulong>());
		FakeObjs.Add(new HashSet<float>());
		FakeObjs.Add(new HashSet<double>());
		FakeObjs.Add(new HashSet<string>());
		FakeObjs.Add((Del_Int)(() => 0));
		FakeObjs.Add((Del_Void)delegate
		{
		});
		FakeObjs.Add(new HashSet<bool>());
		FakeObjs.Add(new HashSet<byte>());
		FakeObjs.Add(new HashSet<ILTypeInstance>());
		new HashSet<byte>().GetEnumerator();
		FakeObjs.Add(new Dictionary<EquipPosition, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<EquipPosition, UGridPanel>());
		FakeObjs.Add(new Dictionary<ILTypeInstance, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<ItemType, UVerticalBox>());
		FakeObjs.Add(new Dictionary<MoneyType, int>());
		FakeObjs.Add(new Dictionary<int, BUI_Button>());
		FakeObjs.Add(new Dictionary<EBGUAttrFloat, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<EBGUAttrFloat, int>());
		FakeObjs.Add(new Dictionary<SpellType, UWidget>());
		FakeObjs.Add(new Dictionary<int, string>());
		FakeObjs.Add(new Dictionary<int, GMMonsterTeleportDesc>());
		FakeObjs.Add(new Dictionary<SpellType, int>());
		FakeObjs.Add(new Dictionary<SpellType, int>());
		FakeObjs.Add(new Dictionary<IFocusWidget, int>());
		FakeObjs.Add(new Dictionary<int, RoomData>());
		FakeObjs.Add(new Dictionary<int, BUI_Button>());
		FakeObjs.Add(new Dictionary<int, string>());
		FakeObjs.Add(new UnorderedDict<ulong, ILTypeInstance>());
		FakeObjs.Add(new UnorderedDict<byte, List<ILTypeInstance>>());
		FakeObjs.Add(new UnorderedDict<string, ILTypeInstance>());
		FakeObjs.Add(new ULevelSequence());
		FakeObjs.Add(new ALevelSequenceActor());
		FakeObjs.Add(new ULevelSequencePlayer());
		FakeObjs.Add(new UTextureRenderTarget2D());
		FakeObjs.Add(new AExponentialHeightFog());
		FakeObjs.Add(new ADirectionalLight());
		FakeObjs.Add(new APostProcessVolume());
		FakeObjs.Add(new UExponentialHeightFogComponent());
		FakeObjs.Add(new ASkyLight());
		FakeObjs.Add(new USkyLightComponent());
		FakeObjs.Add(new UFont());
		FakeObjs.Add(new UMediaPlayer());
		FakeObjs.Add(new UMediaSource());
		FakeObjs.Add(new UProceduralMeshComponent());
		FakeObjs.Add(new ADirectionalLight());
		FakeObjs.Add(new UArrowComponent());
		FakeObjs.Add(new Tuple<ILTypeInstance, ILTypeInstance>(null, null));
		FakeObjs.Add(new URichTextBlock());
		FakeObjs.Add(new USlider());
		FakeObjs.Add(new UWrapBox());
		FakeObjs.Add(new UEditableText());
		FakeObjs.Add(DayOfWeek.Sunday);
		FakeObjs.Add(new DebuggerNonUserCodeAttribute());
		FakeObjs.Add(new ULevelStreamingDynamic());
		FakeObjs.Add(EStringTableLoadingPolicy.Find);
		FakeObjs.Add(new RepeatedField<uint>());
		FakeObjs.Add(ETextJustify.Left);
		FakeObjs.Add(new UTextLayoutWidget());
		FakeObjs.Add(new UMaterialParameterCollection());
		FakeObjs.Add(EDesiredImageFormat.PNG);
		FakeObjs.Add(default(FImageWriteOptions));
		FakeObjs.Add(new UGridSlot());
		FakeObjs.Add(new Dictionary<int, UWidgetAnimation>());
		FakeObjs.Add(new Dictionary<UWidget, float>());
		FakeObjs.Add(new List<ILTypeInstance>());
		FakeObjs.Add(new Queue<Action>());
		FakeObjs.Add(new Tuple<BaseU3.DataSyncFlag, IMessage>(BaseU3.DataSyncFlag.SyncFlagAdd, null));
		FakeObjs.Add(new Tuple<BaseU3.DataSyncFlag, ILTypeInstance>(BaseU3.DataSyncFlag.SyncFlagAdd, null));
		FakeObjs.Add(new NetChannel());
		FakeObjs.Add(new NetChannel.ChannelNotifier());
		FakeObjs.Add(new USafeZone());
		FakeObjs.Add(new List<ServerUnit>());
		FakeObjs.Add(new UnorderedDict<string, ReportMonitorAdd>());
		FakeObjs.Add(new UnorderedDict<string, ReportMonitorSet>());
		FakeObjs.Add(new RepeatedField<ulong>());
		FakeObjs.Add(new BGUDecalActor());
		FakeObjs.Add(new UDecalComponent());
		FakeObjs.Add(new UGSAnimKeyStateBlender());
		FakeObjs.Add(new DirectoryInfo(""));
		FakeObjs.Add(new StringBuilder(""));
		FakeObjs.Add(new UApplicationLifecycleComponent());
		FakeObjs.Add(new UStaticMesh());
		FakeObjs.Add(new UStaticMesh());
		FakeObjs.Add(EMovieScenePositionType.Frame);
		FakeObjs.Add(EUpdatePositionMethod.Play);
		FakeObjs.Add(new UMaterialFunctionInterface());
		FakeObjs.Add(new BUI_Widget());
		FakeObjs.Add(new BGUNetDefaultEmptyActor());
		FakeObjs.Add(new BGG_GameModeB1());
		FakeObjs.Add(new UGeometryCollectionComponent());
		FakeObjs.Add(new Dictionary<AActor, BUI_MInteractIcon>());
		FakeObjs.Add(new Dictionary<ItemPackageType, bool>());
		FakeObjs.Add(new Dictionary<UWidget, int>());
		FakeObjs.Add(new Dictionary<int, PastMemoryDesc>());
		FakeObjs.Add(new GSBindList<ILTypeInstance>());
		FakeObjs.Add(new SortedDictionary<int, UUserWidget>());
		FakeObjs.Add(new Tuple<ResB1.DataSyncFlag, IMessage>(ResB1.DataSyncFlag.SyncFlagAdd, null));
		FakeObjs.Add(new Tuple<ulong, MemberRoleData>(0uL, null));
		FakeObjs.Add(new Dictionary<CSMsgCmd, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<EInputEventType, DateTime>());
		FakeObjs.Add(new Dictionary<EScalabilityQuality, float>());
		FakeObjs.Add(new Dictionary<FKey, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<Type, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<int, UCanvasPanel>());
		FakeObjs.Add(new Dictionary<string, ulong>());
		FakeObjs.Add(new Dictionary<SpellType, ILTypeInstance>());
		FakeObjs.Add(new Tuple<ResB1.DataSyncFlag, IMessage>(ResB1.DataSyncFlag.SyncFlagAdd, null));
		FakeObjs.Add(new Tuple<ResB1.DataSyncFlag, IMessage>(ResB1.DataSyncFlag.SyncFlagAdd, null));
		FakeObjs.Add(new Tuple<int, int>(0, 0));
		FakeObjs.Add(new Tuple<string, string, string>("", "", ""));
		FakeObjs.Add(new Tuple<string, string>("", ""));
		FakeObjs.Add(new Dictionary<APlayerController, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<EUIConfigTab, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<ILTypeInstance, BUI_MBarBase>());
		FakeObjs.Add(new Dictionary<SettingFunTempelte, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<UIConfigType, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<UISettingConfigType, int>());
		FakeObjs.Add(new Dictionary<UUserWidget, ILTypeInstance>());
		FakeObjs.Add(new Dictionary<UUserWidget, float>());
		FakeObjs.Add(new Dictionary<int, bool>());
		FakeObjs.Add(new TStrongObjectPtr<UUserWidget>());
		FakeObjs.Add(new StackTrace(fNeedFileInfo: true));
		FakeObjs.Add(new UBlendSpace1D());
		FakeObjs.Add(new Dictionary<EUINavigation, int>());
		BlittableTypeMarshaler<FProcMeshTangent>.FromNative(IntPtr.Zero);
		BlittableTypeMarshaler<FProcMeshTangent>.ToNative(IntPtr.Zero, default(FProcMeshTangent));
		BlittableTypeMarshaler<FAIStimulus>.FromNative(IntPtr.Zero);
		BlittableTypeMarshaler<FAIStimulus>.ToNative(IntPtr.Zero, default(FAIStimulus));
		FWeightedBlendable.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FWeightedBlendable.FromNative(IntPtr.Zero);
		FWeightedBlendable.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FWeightedBlendable));
		FWeightedBlendable.ToNative(IntPtr.Zero, default(FWeightedBlendable));
		FParticleSysParam.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FParticleSysParam.FromNative(IntPtr.Zero);
		FParticleSysParam.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FParticleSysParam));
		FParticleSysParam.ToNative(IntPtr.Zero, default(FParticleSysParam));
		FSkeletalMaterial.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FSkeletalMaterial.FromNative(IntPtr.Zero);
		FSkeletalMaterial.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FSkeletalMaterial));
		FSkeletalMaterial.ToNative(IntPtr.Zero, default(FSkeletalMaterial));
		FInputActionKeyMapping.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FInputAxisKeyMapping.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FDirectoryPath.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FInputActionKeyMapping.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FInputActionKeyMapping));
		FInputAxisKeyMapping.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FInputAxisKeyMapping));
		FDirectoryPath.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FDirectoryPath));
		FDonNavigationDynamicCollisionPayload.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FDoNNavigationQueryParams.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FDoNNavigationDebugParams.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FDoNNavigationQueryData.FromNative(IntPtr.Zero, 0, IntPtr.Zero);
		FDonNavigationDynamicCollisionPayload.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FDonNavigationDynamicCollisionPayload));
		FDoNNavigationQueryParams.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FDoNNavigationQueryParams));
		FDoNNavigationDebugParams.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FDoNNavigationDebugParams));
		FDoNNavigationQueryData.ToNative(IntPtr.Zero, 0, IntPtr.Zero, default(FDoNNavigationQueryData));
		FakeObjs.Add(new UGSInputComponent());
		FakeObjs.Add(new UEnhancedInputComponent());
		FakeObjs.Add(new UCalliopeNode());
		FakeObjs.Add(new UCalliopeAsset());
		FakeObjs.Add(new ConcurrentQueue<ILTypeInstance>());
		((Type)null).GetMembers();
		ILTypeInstance location = null;
		Interlocked.CompareExchange(ref location, location, location);
		Action<float> location2 = null;
		Interlocked.CompareExchange(ref location2, location2, location2);
		object location3 = null;
		Interlocked.CompareExchange<object>(ref location3, new object(), location3);
		BGW_LogUtil.LogIfNull(FakeObjs, "{0} {1}", 0u, 0u);
		BGW_LogUtil.LogIfNull(FakeObjs, "{0}", 0u);
		if (false)
		{
			_ = 1;
			_ = 1;
			((UFXSystemComponent)null).SetFloatParameter(FName.None, 0f);
			((UFXSystemComponent)null).SetIntParameter(FName.None, 0);
			((USceneComponent)null).Visible = true;
			((USceneComponent)null).RelativeRotation = FRotator.ZeroRotator;
			((USceneComponent)null).AttachTo((USceneComponent)null, default(FName), EAttachLocation.KeepRelativeOffset, bWeldSimulatedBodies: true);
			((USceneComponent)null).AddLocalRotation(FRotator.ZeroRotator, bSweep: false, out FHitResult _, bTeleport: false);
			((USceneComponent)null).SetRelativeRotation(FRotator.ZeroRotator, bSweep: false, out FHitResult _, bTeleport: false);
			((USceneComponent)null).HiddenInGame = true;
			_ = ((USceneComponent)null).HiddenInGame;
			((APostProcessVolume)null).Enabled = false;
			((UNiagaraComponent)null).SetAsset((UNiagaraSystem)null, bResetExistingOverrideParameters: true);
			((UNiagaraComponent)null).ReinitializeSystem();
			((UNiagaraComponent)null).AdvanceSimulation(0, 0f);
			((UFXSystemComponent)null).SetColorParameter(default(FName), default(FLinearColor));
			((UParticleSystemComponent)null).SetTemplate(new UParticleSystem());
			((UAnimInstance)null).Montage_JumpToSection(new FName(""), (UAnimMontage)null);
			((UAnimInstance)null).Montage_IsActive((UAnimMontage)null);
			((UAnimInstance)null).Montage_JumpToSectionsEnd(new FName(""), (UAnimMontage)null);
			((UAnimInstance)null).Montage_Play((UAnimMontage)null, 1f, EMontagePlayReturnType.MontageLength, 0f, bStopAllMontages: true);
			((UAnimInstance)null).Montage_SetNextSection(new FName(""), new FName(""), (UAnimMontage)null);
			((UAnimInstance)null).Montage_SetPlayRate((UAnimMontage)null, 0f);
			((UAnimInstance)null).Montage_Stop(0f, (UAnimMontage)null);
			FRotator.ZeroRotator.EqualEqual_RotatorRotator(FRotator.ZeroRotator);
			_ = ((AActor)null).Hidden;
			((ALevelSequenceActor)null).SetSequence((ULevelSequence)null);
			((ALevelSequenceActor)null).AddBindingByTag(default(FName), (AActor)null, bAllowBindingsFromAsset: false);
			((ALevelSequenceActor)null).RemoveBindingByTag(default(FName), (AActor)null);
			((UMovieSceneSequencePlayer)null).Play();
			((UMovieSceneSequencePlayer)null).Pause();
			((UMovieSceneSequencePlayer)null).Stop();
			((AActor)null).SetActorTickEnabled(bEnabled: false);
			((AActor)null).SetActorTickInterval(0f);
			UMediaPlayer uMediaPlayer = new UMediaPlayer();
			uMediaPlayer.OpenSource(new UMediaSource());
			uMediaPlayer.Play();
			JsonMapper.ToJson(null);
			JsonMapper.ToObject(new JsonReader(""));
			JsonMapper.ToObject("");
			JsonMapper.ToObject<ILTypeInstance>(new JsonReader(""));
			JsonMapper.ToObject<ILTypeInstance>("");
			_ = new UPaperSprite().PathName;
			((UActorComponent)null).Deactivate();
			((UActorComponent)null).Activate(bReset: true);
			((USceneComponent)null).ResetRelativeTransform();
			((UTexture)null).ExportToDisk(null, default(FImageWriteOptions));
			FVector2D A = default(FVector2D);
			A.Normalize2D();
			0L.ToString("");
			new List<int>().GetRange(0, 0);
			DateTime dateTime = default(DateTime);
			dateTime.AddMinutes(1.0);
			dateTime.AddHours(1.0);
			((JsonData)null)[0].ToJson();
			((JsonData)null)["test"].ToJson();
			((JsonData)null).Keys.Contains("test");
			ulong.Parse("0");
			bool.Parse("false");
			uint result = 0u;
			uint.TryParse("", out result);
			bool lockTaken = false;
			Monitor.Enter(null, ref lockTaken);
			ThreadPool.QueueUserWorkItem(null, null);
			Monitor.Enter(null);
			Monitor.Exit(null);
			GSEUtil.LockEnter(null);
			GSEUtil.LockExit(null);
			((ALevelSequenceActor)null).PlaybackSettings = default(FMovieSceneSequencePlaybackSettings);
			List<int> first = new List<int>();
			List<int> second = new List<int>();
			first.Except(second);
			first.Intersect(second);
			new List<ServerUnit>();
			UAudioComponent uAudioComponent = new UAudioComponent();
			uAudioComponent.IsPlaying();
			_ = uAudioComponent.Sound.Duration;
			uAudioComponent.Play();
			uAudioComponent.Stop();
			"hello".IndexOf(' ', 0, 1);
			"hello".IndexOf("", 0, 1);
			BitConverter.ToString(new byte[100]);
			File.ReadAllText("");
			File.WriteAllText("", "hello");
			Convert.ToUInt32("4");
			UGSE_FileFuncLib.AndroidExtractFolderFromApk("", "");
			Regex.IsMatch("IsMatch Ref", "[\"]");
			FileSystemInfo obj = new DirectoryInfo("").GetFileSystemInfos("*")[0];
			_ = obj.FullName;
			MD5 mD = new MD5CryptoServiceProvider();
			Directory.Exists(obj.FullName);
			FileStream fileStream = new FileStream(obj.FullName, FileMode.Open);
			mD.ComputeHash(fileStream);
			fileStream.Close();
			new UApplicationLifecycleComponent().ApplicationWillEnterBackgroundDelegate.Bind(null);
			new UApplicationLifecycleComponent().ApplicationHasEnteredForegroundDelegate.Bind(null);
			Array values = Enum.GetValues(typeof(Type));
			bool forceMipStreaming = new UPrimitiveComponent().ForceMipStreaming;
			values.GetEnumerator();
			new Random().Next();
			float num = 0f;
			float value = 0f;
			num.CompareTo(value);
			value = (float)default(FVector2D).Distance2D(default(FVector2D));
			((UFXSystemComponent)null).SetEmitterEnable(default(FName), forceMipStreaming);
			_ = ((UMovieSceneSequencePlayer)null).OnPlay;
			_ = ((APlayerController)null).ShowMouseCursor;
			_ = default(FKey).IsGamepadKey;
			((AActor)null).DisableInput((APlayerController)null);
			((AActor)null).EnableInput((APlayerController)null);
			((Type)null).GetMethods();
			Convert.ToInt32(0f);
			new TimeSpan(0, 0, 0);
			new UMatineeCameraShake();
			new UPostProcessComponent().Enabled = true;
			((AController)null).IsLocalController();
			((UMediaPlayer)null).SetLooping(Looping: true);
			((UMediaPlayer)null).Close();
			BGW_LogUtil.LogError("111111111111111", P1: true);
			new UFileMediaSource();
			FApp.HasProjectName();
			_ = new APlayerState().GetPlayerController() != null;
			DateTimeOffset.FromUnixTimeSeconds(0L).ToLocalTime().ToString("yyyy/MM/dd");
			GroupCollection groupCollection = null;
			if (groupCollection != null)
			{
				_ = groupCollection.Count;
				_ = 0;
			}
			"".GetHashCode();
			_ = ((IPHostEntry)null)?.AddressList.LongLength;
			Dns.GetHostEntry("");
			_ = ((TimeZoneInfo)null)?.BaseUtcOffset;
			_ = TimeZoneInfo.Local;
			BGW_LogUtil.LogError("xxx%s", P1: false);
			BGW_LogUtil.LogError("xxx%s", 0);
			BGW_LogUtil.LogError("xxx%s", "");
			BGW_LogUtil.LogError("xxx%s%s%s", "", "", "");
			UMediaPlayer uMediaPlayer2 = null;
			if (uMediaPlayer2 != null)
			{
				_ = uMediaPlayer2.OnEndReached;
			}
			_ = 3;
			_ = 3;
			JsonWriter jsonWriter = new JsonWriter();
			jsonWriter?.TextWriter.Close();
			jsonWriter.PrettyPrint = true;
			JsonMapper.ToJson(null);
			JsonMapper.ToJson(null, jsonWriter);
			Process process = new Process();
			if (process.ExitCode > 0)
			{
				process.WaitForExit();
			}
			ProcessStartInfo processStartInfo = (process.StartInfo = new ProcessStartInfo(""));
			Process.Start("", "");
			UPaths.ProjectPersistentDownloadDir();
			new StreamWriter("", append: false, Encoding.UTF8);
			new AActor().SetActorRelativeScale3D(new FVector(0f));
			processStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
			processStartInfo.WorkingDirectory = "";
			Directory.Delete("", recursive: false);
			ValueType valueType = null;
			if (valueType != null)
			{
				valueType.GetHashCode();
				_ = 0;
			}
			((MatchCollection)null).GetEnumerator();
			File.ReadAllText("null", Encoding.UTF8);
			UGameUserSettings uGameUserSettings = new UGameUserSettings();
			uGameUserSettings.SetResolutionScaleValueEx(0f);
			uGameUserSettings.GetResolutionScaleInformationEx(out var _, out var _, out var _, out var _);
			((FileInfo)null)?.CopyTo("");
			ulong value2 = 0uL;
			value2.CompareTo(value2);
			new ANavigationData();
			new ANavMeshBoundsVolume();
			new UDestructibleMesh();
			new UScaleBox();
			new TObjectIterator<UEnum>();
			new TObjectIterator<UFunction>();
			new TObjectIterator<UStruct>();
			new TObjectIterator<UClass>();
			BGW_LogUtil.LogError(((Delegate)null).GetMethodInfo().Name ?? "");
			((Action)delegate
			{
				((Action<string, Action>)delegate
				{
				})("hello", delegate
				{
				});
			})();
			new SemaphoreSlim(0).Release();
			new CancellationTokenSource().Cancel();
			new TaskCompletionSource<bool>().SetResult(result: true);
		}
	}
}
