using System.Collections.Generic;
using BtlB1;

namespace b1;

public static class AttackHitAKNameMapping
{
	public static readonly Dictionary<EHitPerformAudioEventType, string> HitPerformTypeNameMap = new Dictionary<EHitPerformAudioEventType, string>
	{
		{
			EHitPerformAudioEventType.NormalHit,
			"normal"
		},
		{
			EHitPerformAudioEventType.CritHit,
			"critical"
		},
		{
			EHitPerformAudioEventType.SkillSurperArmorHit,
			"skillsuperarmor"
		},
		{
			EHitPerformAudioEventType.ParryHit,
			"parry"
		},
		{
			EHitPerformAudioEventType.BlockArmorHit,
			"block"
		},
		{
			EHitPerformAudioEventType.PerfectBlockArmorHit,
			"perfectblock"
		},
		{
			EHitPerformAudioEventType.SkillSurperArmorBreakHit,
			"skillsuperarmorbreak"
		},
		{
			EHitPerformAudioEventType.BlockArmorBreakHit,
			"blockbreak"
		},
		{
			EHitPerformAudioEventType.ImmobilizedHit,
			"immobilizedhit"
		},
		{
			EHitPerformAudioEventType.ImmobilizedBreakHit,
			"immobilizedbreak"
		},
		{
			EHitPerformAudioEventType.PartBreakHit,
			"partbreak"
		},
		{
			EHitPerformAudioEventType.FrozenHit,
			"frozenhit"
		},
		{
			EHitPerformAudioEventType.FrozenBreakHit,
			"frozenbreakhit"
		}
	};

	public static readonly Dictionary<EHitItemAudioType, string> HitItemTypeNameMap = new Dictionary<EHitItemAudioType, string>
	{
		{
			EHitItemAudioType.NormalBody,
			"meat"
		},
		{
			EHitItemAudioType.Metal,
			"metal"
		},
		{
			EHitItemAudioType.Wooden,
			"wood"
		},
		{
			EHitItemAudioType.Stone,
			"stone"
		},
		{
			EHitItemAudioType.Bone,
			"bone"
		},
		{
			EHitItemAudioType.MetalShield,
			"shieldmetal"
		},
		{
			EHitItemAudioType.WoodenShield,
			"shieldwood"
		},
		{
			EHitItemAudioType.Frozen,
			"frozen"
		},
		{
			EHitItemAudioType.SoftWooden,
			"softwooden"
		},
		{
			EHitItemAudioType.SoftInsect,
			"softinsect"
		},
		{
			EHitItemAudioType.HardInsect,
			"hardinsect"
		}
	};
}
