using UnrealEngine.Runtime;

namespace b1;

[BlueprintType]
[UEnum]
[USharpPath("/Script/b1-Managed.EBUStateTrigger")]
public enum EBUStateTrigger : byte
{
	None = 0,
	Die = 1,
	Rebirth = 2,
	CastSkillSuccess = 3,
	AttackStateBegin = 4,
	AttackRotationBegin = 5,
	SkillBreak = 6,
	Beatback = 7,
	EnterComboWindow = 8,
	AtkRebounding = 9,
	UnitInputWalkPressed = 10,
	UnitInputWalkRelease = 11,
	UnitInputSprintPressed = 12,
	UnitInputSprintRelease = 13,
	BreakSprint = 14,
	EnableMoveInSkill = 15,
	EnterAtkComboKeyCache = 16,
	EnterDodgeComboKeyCache = 17,
	EnterDodgeWindow = 18,
	EnterMagicKeyCache = 19,
	EnterMagicWindow = 20,
	HRCounterattackBegin = 21,
	ShooterModeTrigger = 22,
	ShooterModeClear = 23,
	BMMoveAttackTrigger = 24,
	BMMoveAttackClear = 25,
	AttackAlignUpperBodyToSlopeBegin = 26,
	AttackAlignWholeBodyToSlopeBegin = 27,
	JumpMovingStart = 28,
	JumpMovingStop = 29,
	ShootModeTigger = 30,
	ShootModeClear = 31,
	AIInputSprint = 32,
	AIInputRun = 33,
	AIInputWalk = 34,
	BeginFloatingHit = 35,
	EndFloatingHit = 36,
	EnterGlideMove = 37,
	EndGlideMove = 38,
	EnterMoveWindow = 39,
	EnterBlockBeatBack = 70,
	EnterPerfectBlockBeatBack = 71,
	EnterBlockBounced = 72,
	LeaveAllBlockState = 73,
	FreezeAccProtectBegin = 74,
	EnableImpactAction = 75,
	EnterBlindStiff = 76,
	TeleportBegin = 77,
	TeleportEnd = 78,
	EnterAbortWindow = 79,
	EnterAnimationSyncDeathWindow = 80,
	EnterJumpWindow = 81,
	ExitJumpWindow = 82,
	StartJump = 83,
	StartMoveInMoveWindow = 84,
	EnterPhasePerformance = 85,
	ExitPhasePerformance = 86,
	Enter_LifeSavingHair_FakeDead = 87,
	Enter_LifeSavingHair_Rebirth = 88,
	Exit_LifeSavingHair = 89,
	EnterVigorKeyCache = 90,
	EnterVigorWindow = 91,
	EnterItemSkillKeyCache = 92,
	EnterItemSkillWindow = 93,
	EnterLifeSavingHairBlocking = 94,
	ExitLifeSavingHairBlocking = 95,
	EnterInteractWindow = 96,
	EnterCloudWindow = 97,
	EnterChapterClearWorkFlow = 98,
	ExitChapterClearWorkFlow = 99,
	EnumMax = 100
}
