using UnrealEngine.Runtime;

namespace b1;

[UEnum]
[BlueprintType]
[USharpPath("/Script/b1-Managed.DetectedElementType")]
public enum EDetectedElementType : byte
{
	[UMeta(MD.Hidden)]
	None,
	[DisplayName("是否拥有SimpleState")]
	SimpleState,
	[DisplayName("是否拥有UnitState")]
	UnitState,
	[DisplayName("是否拥有Buff")]
	HasBuff,
	[DisplayName("检查属性值")]
	UnitAttr,
	[Tooltip("使用是否有目标来判断激活状态")]
	[DisplayName("是否激活（有目标）")]
	UnitActived,
	[Tooltip("使用是否有目标来判断激活状态")]
	[DisplayName("是否没激活（没有目标）")]
	UnitInActived,
	[DisplayName("异常状态")]
	AbnormalState,
	[DisplayName("检查Fsm状态（指定几个）")]
	FsmState,
	[DisplayName("是否技能冷却中")]
	SkillCoolDown,
	[DisplayName("到目标的距离")]
	DistanceFromTarget,
	[DisplayName("技能满足可释放条件")]
	SkillCanCast,
	[DisplayName("检查Fsm状态（自定义）")]
	CustomFsmState,
	[DisplayName("上一次受击挡位")]
	LastBeAttackedStiffLevel,
	[DisplayName("到Master的距离")]
	DistanceFromMaster,
	[Tooltip("判断当前角色的Rotation是否在夹角范围内，即以基准朝向作为0度，从最小Yaw值到最大Yaw值的夹角范围")]
	[DisplayName("角色朝向是否在夹角内")]
	ActorYawRotation,
	[DisplayName("技能释放次数全局比较")]
	GlobalCastSkillCount,
	[DisplayName("使用技能中")]
	DurCastSkill,
	[DisplayName("当前受击挡位")]
	CurrentBeAttackedStiffLevel,
	[DisplayName("造成伤害次数")]
	CurSkillCostDmgNum,
	[DisplayName("挂点子角色全部死亡")]
	SocketUnitsDead,
	[DisplayName("和最近的玩家的距离")]
	DistanceFromNearestPlayer,
	[DisplayName("指定ResID的子角色全部死亡")]
	SpecifyResIdUnitsDead,
	[DisplayName("Circus特定单位Attr")]
	FamilySpecifyUnitAttr,
	[DisplayName("概率随机")]
	Random,
	[DisplayName("Circus存活单位数量")]
	FamilyUnitAliveNum,
	[DisplayName("目标是否在夹角内")]
	[Tooltip("判断目标是否在夹角范围内，即以当前角色朝向作为0度，从最小Yaw值到最大Yaw值的夹角范围")]
	TargetInAngleRange,
	[DisplayName("比较Buff层数")]
	CompareBuffLayer,
	[DisplayName("比较周目数")]
	CompareGamePlusCount,
	[DisplayName("脚下物理材质")]
	CheckSurfaceType,
	[DisplayName("当前区域还有故事会可说")]
	HasStoryCanTalkInThisLevel,
	[DisplayName("故事会讲述处于冷静期")]
	StoryInCollingOffPeriod,
	[DisplayName("玩家摸鱼观战时间太长(只跟随八戒可用)")]
	PlayerLeisureOverTime
}
