using UnrealEngine.Runtime;

namespace b1;

[UEnum]
[BlueprintType]
[USharpPath("/Script/b1-Managed.ObModeSource")]
public enum EObModeSource : byte
{
	[DisplayName("空")]
	Null,
	[DisplayName("古玩文物")]
	Antique,
	[DisplayName("历史文萃")]
	Artifact,
	[DisplayName("物品界面")]
	Item,
	[DisplayName("装备主界面")]
	MainEquip,
	[DisplayName("装备头部")]
	EquipHead,
	[DisplayName("装备衣服")]
	EquipUpwear,
	[DisplayName("装备臂甲")]
	EquipArm,
	[DisplayName("装备腿甲")]
	EquipFoot,
	[DisplayName("装备葫芦")]
	EquipHulu,
	[DisplayName("装备武器")]
	EquipWeapon,
	[DisplayName("装备法宝")]
	EquipFabao,
	[DisplayName("装备护符")]
	EquipAccessory,
	[DisplayName("装备精魄")]
	EquipSoul,
	[DisplayName("泡酒默认")]
	SoakingMain,
	[DisplayName("泡酒酒")]
	SoakingLiquor,
	[DisplayName("泡酒消耗品一")]
	SoakingConsume1,
	[DisplayName("泡酒消耗品二")]
	SoakingConsume2,
	[DisplayName("泡酒消耗品三")]
	SoakingConsume3,
	[DisplayName("泡酒消耗品四")]
	SoakingConsume4,
	[DisplayName("大圣遗物")]
	Legacy,
	[DisplayName("炼丹")]
	MedicineRecipe,
	[UMeta(MD.Hidden)]
	Black,
	[UMeta(MD.Hidden)]
	Spell,
	[UMeta(MD.Hidden)]
	Ability,
	[UMeta(MD.Hidden)]
	Setting,
	[UMeta(MD.Hidden)]
	Manual,
	[UMeta(MD.Hidden)]
	TravelNotesMain,
	[UMeta(MD.Hidden)]
	LegacyEven,
	[UMeta(MD.Hidden)]
	LegacyOdd,
	[UMeta(MD.Hidden)]
	AbilitySwitch,
	[UMeta(MD.Hidden)]
	SpellSwitch,
	[UMeta(MD.Hidden)]
	EquipMainSwitch,
	[UMeta(MD.Hidden)]
	ItemSwitch,
	[UMeta(MD.Hidden)]
	TNMSwitch,
	[UMeta(MD.Hidden)]
	ManualSwitch,
	[UMeta(MD.Hidden)]
	SettingSwitch,
	[UMeta(MD.Hidden)]
	LegacySwitch,
	[UMeta(MD.Hidden)]
	EquipSoulSwitch,
	[UMeta(MD.Hidden)]
	BlackSwitch,
	[UMeta(MD.Hidden)]
	EquipFabaoSwitch,
	[UMeta(MD.Hidden)]
	EquipAccessorySwitch,
	[UMeta(MD.Hidden)]
	MedicineRecipeSwitch,
	[UMeta(MD.Hidden)]
	BossRushSwitch,
	[UMeta(MD.Hidden)]
	BossRush1,
	[UMeta(MD.Hidden)]
	BossRush2,
	[UMeta(MD.Hidden)]
	BossRush3,
	[UMeta(MD.Hidden)]
	BossRush4,
	[UMeta(MD.Hidden)]
	BossRush5,
	[UMeta(MD.Hidden)]
	BossRush6
}
