namespace b1;

public enum EPropType
{
	None = 0,
	Movement_OrientRotationToMovement = 1,
	Movement_RotationRate = 2,
	Movement_BrakingDecelerationWalking = 3,
	Movement_MaxAcceleration = 4,
	Movement_GroundFriction = 5,
	Movement_CanWalkOffLedges = 6,
	Movement_AllowPhysicsRotationDuringAnimRootMotion = 7,
	Movement_MaxCustomMovementSpeed = 8,
	Movement_MaxFlySpeed = 9,
	Movement_MaxSwimSpeed = 10,
	Movement_MaxWalkSpeedCrouched = 11,
	Movement_MaxWalkSpeed = 12,
	Movement_MovementMode = 13,
	Movement_GravityScale = 14,
	Movement_BrakingFrictionFactor = 15,
	Movement_BrakingFriction = 16,
	Movement_SpeedCtrlInfo = 17,
	Mesh_EnableGravity = 101,
	Mesh_PauseAnims = 102,
	Mesh_HiddenInGame = 103,
	Mesh_Visibility = 104,
	Mesh_CollisionEnabled = 105,
	Mesh_CollisionObjectType = 106,
	Mesh_CollisionProfileName = 107,
	Mesh_CollisionResponseToChannels = 108,
	Mesh_EnableFootIK = 109,
	Capsule_EnableGravity = 201,
	Capsule_CollisionEnabled = 202,
	Capsule_CollisionObjectType = 203,
	Capsule_CollisionProfileName = 204,
	Capsule_CollisionResponseToChannels = 205,
	Actor_CustomTimeDilation = 301,
	Actor_ActorHiddenInGame = 302,
	Actor_AttackerAbnormalDispID_Override = 303
}
