using UnrealEngine.Runtime;

namespace b1;

[UEnum]
[BlueprintType]
[USharpPath("/Script/b1-Managed.EUIPageID")]
public enum EUIPageID : byte
{
	MIN,
	[DisplayName("UI管理")]
	Managed,
	[DisplayName("战斗主界面UICon")]
	BattleMainCon,
	[DisplayName("剧情故事UI")]
	Story,
	[DisplayName("队伍信息UI")]
	TeamInfo,
	[DisplayName("血条信息UI")]
	BloodBarList,
	[DisplayName("交互UI")]
	Interact,
	[DisplayName("复活点主界面")]
	ShrineMain,
	[DisplayName("濒死UI")]
	FallDying,
	[DisplayName("死亡UI")]
	Death,
	[DisplayName("瞄准UI")]
	TPSReticle,
	[DisplayName("名字UI")]
	Name,
	[DisplayName("角色主页")]
	RoleMain,
	[DisplayName("角色主页背景")]
	Background,
	[DisplayName("装备主页")]
	EquipMain,
	[DisplayName("背包主页")]
	BagMain,
	[DisplayName("掉落主页")]
	MDropMain,
	[DisplayName("特殊掉落")]
	DropSpecial,
	[DisplayName("黑屏UI")]
	BlackOut,
	[DisplayName("开始游戏Managed")]
	StartGameManaged,
	[DisplayName("开始游戏")]
	StartGame,
	[DisplayName("适龄提示")]
	AgeTips,
	[DisplayName("读档界面")]
	Archives,
	[DisplayName("选择章节")]
	SelectChapter,
	[DisplayName("击杀慢镜头UI")]
	Defeated,
	[DisplayName("商店")]
	Shop,
	[DisplayName("防具商店")]
	EquipShop,
	[DisplayName("二次确认")]
	Confirm,
	[DisplayName("三键二次确认")]
	ConfirmThree,
	[DisplayName("修行")]
	TalentMain,
	[DisplayName("天赋学习")]
	LearnTalent,
	[DisplayName("大圣天赋学习")]
	LearnLegacyTalent,
	[DisplayName("地图Tips")]
	MapTips,
	[DisplayName("设置")]
	Setting,
	[DisplayName("登录初始设置")]
	InitSetting,
	[DisplayName("键鼠按键设置")]
	SettingInputKeyBoard,
	[DisplayName("画面详细设置")]
	SettingScreenDetail,
	[DisplayName("亮度设置")]
	BrightnessSetting,
	[DisplayName("HDR")]
	HDRSetting,
	[DisplayName("通用提示UI")]
	CommTips,
	[DisplayName("通用提示UI")]
	CommTipsBlock,
	[DisplayName("泡酒")]
	SoakingMain,
	[DisplayName("奖励UI")]
	Award,
	[DisplayName("炼丹")]
	MedicineRecipe,
	[DisplayName("炼丹")]
	Alchemy,
	[DisplayName("通用跳过UI")]
	CommSkip,
	[DisplayName("武器锻造")]
	WeaponBuild,
	[DisplayName("武器锻造")]
	RoleWeaponBuild,
	[DisplayName("防具锻造")]
	EquipBuild,
	[DisplayName("UI输入阻挡层")]
	AnimShowBlock,
	[DisplayName("简易说明Tips")]
	SimpleTips,
	[DisplayName("NpcInteract界面")]
	NpcInteract,
	[DisplayName("图鉴主页")]
	CollectionMain,
	[DisplayName("章节奖励UI")]
	ChapterAward,
	[DisplayName("章节Movie")]
	ChapterMovie,
	[DisplayName("游记入口")]
	TravelNotesMain,
	[DisplayName("前尘影事")]
	PastMemory,
	[DisplayName("打坐点")]
	RoleMeditationPointMain,
	[DisplayName("影片播放器")]
	SeqMediaPlayer,
	[DisplayName("存档Tips")]
	SaveTips,
	[DisplayName("登录UI")]
	Login,
	[DisplayName("登录说明UI")]
	LoginNotice,
	[DisplayName("政策协议")]
	AgreementPolicy,
	[DisplayName("收获药材")]
	Farm,
	[DisplayName("变身操作提示UI")]
	TransGuide,
	[DisplayName("新手引导浮窗")]
	GuideNormal,
	[DisplayName("新手引导任务清单")]
	GuideQuest,
	[DisplayName("新手引导弹窗")]
	GuidePopbox,
	[DisplayName("拍照系统")]
	TakePhoto,
	[DisplayName("成就提示")]
	AchieveTips,
	[DisplayName("QTE交互")]
	QTEInteract,
	[DisplayName("EndCredits")]
	EndCredits,
	[DisplayName("精魄拾遗")]
	SoulSkillCollect,
	[DisplayName("精魄强化")]
	SoulSkillStrength,
	[DisplayName("性能跑分")]
	BenchMark,
	[DisplayName("葫芦强化")]
	HuluStrength,
	[DisplayName("酒强化")]
	WineStrength,
	[DisplayName("新手指导")]
	GuideMain,
	[DisplayName("版本奖励")]
	EditionAward,
	[DisplayName("编译PSO进度条")]
	ShaderCompiling,
	[DisplayName("PlayGo进度条")]
	PlayGoProgressRaw,
	[DisplayName("PlayGo进度条")]
	PlayGoProgressNormal,
	[DisplayName("乐坊")]
	SoundtrackV2,
	[DisplayName("seq LogoUI")]
	SeqLogo,
	[DisplayName("多周目教学")]
	NewGamePlusGuide,
	[DisplayName("Loading 衔接")]
	LoadingAdaptor,
	[DisplayName("编译PSO确认")]
	ShaderCompilingConfirm,
	[DisplayName("地图UI")]
	Map,
	[DisplayName("Debug地图UI")]
	DebugMap,
	[DisplayName("PS5小曲音频导出")]
	MusicExport,
	[DisplayName("Boss再战主页")]
	BossReChallengeMain,
	[DisplayName("Boss连战主页")]
	BossIterationsMain,
	[DisplayName("BossRush战斗结算")]
	BossRushSettlement,
	[DisplayName("BossRush TimeUI")]
	BossRushTime,
	[DisplayName("Boss连战奖励")]
	BossIterationsAward,
	[DisplayName("BossRush开始战斗倒计时")]
	BossRushStartFight,
	[DisplayName("迷你GM")]
	MiniGM,
	[DisplayName("GM二次确认")]
	GMConfirm,
	[DisplayName("GM通用提示UI")]
	GMCommTips,
	[DisplayName("崩溃上报UI")]
	ReportBugPanel,
	[DisplayName("Texture配置校验")]
	UITexConfigCheck,
	[DisplayName("测试HEX UI")]
	HexRoomTest,
	[DisplayName("GuiqiangTest")]
	GuiqiangTest,
	[DisplayName("测试UI")]
	HatumTestUI,
	[DisplayName("EllenTest")]
	EllenTest,
	[DisplayName("GM展示UI文本")]
	GMDisplayUIText,
	EnumMax
}
