using UnrealEngine.Runtime;

namespace b1;

[BlueprintType]
[UEnum]
[USharpPath("/Script/b1-Managed.EUIPageType")]
public enum EUIPageType : byte
{
	[DisplayName("最小值")]
	None,
	[DisplayName("修行")]
	Practice,
	[DisplayName("披挂")]
	Equip,
	[DisplayName("行囊")]
	Bag,
	[DisplayName("货殖")]
	Shop,
	[DisplayName("武器锻造")]
	WeaponBuild,
	[DisplayName("防具升级")]
	EquipBuild,
	[DisplayName("防具制作")]
	EquipShop,
	[DisplayName("泡酒")]
	SoakingMain,
	[DisplayName("炼制普通丹药")]
	RefiningCommonElixir,
	[DisplayName("炼制小仙丹")]
	RefiningElixir,
	[DisplayName("葫芦升级")]
	HuluLevel,
	[DisplayName("酒升级")]
	WineLevel,
	[DisplayName("收获药材")]
	Farm,
	[DisplayName("游记")]
	TravelNotes,
	[DisplayName("章节中转")]
	ChapterAward,
	[DisplayName("大圣天赋学习")]
	LearnLegacyTalent,
	[DisplayName("精魄拾遗")]
	SoulSkillCollect,
	[DisplayName("BenchMark")]
	BenchMark,
	[DisplayName("读档")]
	Archives,
	[DisplayName("设置")]
	Setting,
	[DisplayName("字幕")]
	Story,
	[DisplayName("铭牌")]
	Name,
	[DisplayName("影片播放器")]
	SeqMediaPlayer,
	[DisplayName("天赋学习")]
	LearnTalent,
	[DisplayName("版本奖励")]
	EditionAward,
	[DisplayName("照相系统")]
	TakePhoto,
	[DisplayName("观察模式")]
	ObsMode,
	[DisplayName("法宝界面")]
	FaBao,
	[DisplayName("人种袋界面 ")]
	SoulSkill,
	[DisplayName("缩地")]
	Teleport,
	[DisplayName("设置HDR")]
	SettingHDR,
	[DisplayName("设置亮度")]
	SettingBrightness,
	[DisplayName("设置键盘输入")]
	SettingKeyBoard,
	[DisplayName("Seq Logo")]
	SeqLogo,
	[DisplayName("前尘影事")]
	PastMemory,
	[DisplayName("乐坊")]
	SoundtrackV2,
	[DisplayName("EndingCredits")]
	EndCredits,
	[DisplayName("地图")]
	Map,
	[DisplayName("BossRush结算")]
	BossRushSettlement,
	[DisplayName("BossRush再战")]
	BossRushReChallenge,
	[DisplayName("BossRush连战")]
	BossRushIterations,
	[DisplayName("BossRush连战奖励")]
	BossRushIterationsAward
}
