<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>b1.Managed</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnrealEngine.Runtime">
      <HintPath>..\UnrealEngine.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="GSE.Core">
      <HintPath>..\GSE.Core.dll</HintPath>
    </Reference>
    <Reference Include="BtlSvr.Main">
      <HintPath>..\BtlSvr.Main.dll</HintPath>
    </Reference>
    <Reference Include="UnrealEngine">
      <HintPath>..\UnrealEngine.dll</HintPath>
    </Reference>
    <Reference Include="b1.NativePlugins">
      <HintPath>..\b1.NativePlugins.dll</HintPath>
    </Reference>
    <Reference Include="ILRuntime">
      <HintPath>..\ILRuntime.dll</HintPath>
    </Reference>
    <Reference Include="LitJson">
      <HintPath>..\LitJson.dll</HintPath>
    </Reference>
    <Reference Include="b1.Native">
      <HintPath>..\b1.Native.dll</HintPath>
    </Reference>
    <Reference Include="Google.Protobuf">
      <HintPath>..\Google.Protobuf.dll</HintPath>
    </Reference>
    <Reference Include="GSE.ProtobufDB">
      <HintPath>..\GSE.ProtobufDB.dll</HintPath>
    </Reference>
    <Reference Include="Protobuf.RunTime">
      <HintPath>..\Protobuf.RunTime.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="GSE.GSNet">
      <HintPath>..\GSE.GSNet.dll</HintPath>
    </Reference>
    <Reference Include="GSE.GSSdk">
      <HintPath>..\GSE.GSSdk.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>