namespace b1.CppExport;

public static class AsyncLineTraceReqLib
{
	public static GSE_AsyncLineTraceReqFunc.Del_AsyncLineTraceReqArrayRef_Allocate AsyncLineTraceReqArrayRef_Allocate;

	public static GSE_AsyncLineTraceReqFunc.Del_AsyncLineTraceReqArrayRef_Add AsyncLineTraceReqArrayRef_AddReq;

	public static GSE_AsyncLineTraceReqFunc.Del_AsyncLineTraceReqArrayRef_Destroy AsyncLineTraceReqArrayRef_Destroy;

	public static GSE_AsyncLineTraceReqFunc.Del_AsyncLineTraceReqArrayRef_GetReqID AsyncLineTraceReqArrayRef_GetReqID;

	public static GSE_AsyncLineTraceReqFunc.Del_AsyncLineTraceReqArrayRef_GetReqNum AsyncLineTraceReqArrayRef_GetReqNum;

	static AsyncLineTraceReqLib()
	{
		new GSE_AsyncLineTraceReqFunc();
	}
}
