using UnrealEngine.Engine;

namespace b1.EventDelDefine;

public delegate void Del_BeginManualSplineMoveWithSpecialAnimation(USplineComponent TargetSpline, BGWDataAsset_ManualSplineMoveAnimConfig MoveAnimConfig);
