using System;
using System.Runtime.CompilerServices;
using UnrealEngine.Engine;
using UnrealEngine.Runtime;

namespace UnrealEngine.Plugins.AnimationLocomotionLibraryRuntime;

[UClass(Flags = (ClassFlags)810549408uL, Config = "Engine")]
[UMetaPath("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary", "AnimationLocomotionLibraryRuntime", UnrealModuleType.EnginePlugin)]
public class UAnimCharacterMovementLibrary : UBlueprintFunctionLibrary
{
	private static IntPtr classAddress;

	private static bool PredictGroundMovementStopLocation_IsValid;

	private static IntPtr PredictGroundMovementStopLocation_FunctionAddress;

	private static int PredictGroundMovementStopLocation_ParamsSize;

	private static bool PredictGroundMovementStopLocation_Velocity_IsValid;

	private static FFieldAddress PredictGroundMovementStopLocation_Velocity_PropertyAddress;

	private static int PredictGroundMovementStopLocation_Velocity_Offset;

	private static bool PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_IsValid;

	private static FFieldAddress PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_PropertyAddress;

	private static int PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_Offset;

	private static bool PredictGroundMovementStopLocation_BrakingFriction_IsValid;

	private static FFieldAddress PredictGroundMovementStopLocation_BrakingFriction_PropertyAddress;

	private static int PredictGroundMovementStopLocation_BrakingFriction_Offset;

	private static bool PredictGroundMovementStopLocation_GroundFriction_IsValid;

	private static FFieldAddress PredictGroundMovementStopLocation_GroundFriction_PropertyAddress;

	private static int PredictGroundMovementStopLocation_GroundFriction_Offset;

	private static bool PredictGroundMovementStopLocation_BrakingFrictionFactor_IsValid;

	private static FFieldAddress PredictGroundMovementStopLocation_BrakingFrictionFactor_PropertyAddress;

	private static int PredictGroundMovementStopLocation_BrakingFrictionFactor_Offset;

	private static bool PredictGroundMovementStopLocation_BrakingDecelerationWalking_IsValid;

	private static FFieldAddress PredictGroundMovementStopLocation_BrakingDecelerationWalking_PropertyAddress;

	private static int PredictGroundMovementStopLocation_BrakingDecelerationWalking_Offset;

	private static bool PredictGroundMovementStopLocation_ReturnValue_IsValid;

	private static FFieldAddress PredictGroundMovementStopLocation_ReturnValue_PropertyAddress;

	private static int PredictGroundMovementStopLocation_ReturnValue_Offset;

	private static bool PredictGroundMovementPivotLocation_IsValid;

	private static IntPtr PredictGroundMovementPivotLocation_FunctionAddress;

	private static int PredictGroundMovementPivotLocation_ParamsSize;

	private static bool PredictGroundMovementPivotLocation_Acceleration_IsValid;

	private static FFieldAddress PredictGroundMovementPivotLocation_Acceleration_PropertyAddress;

	private static int PredictGroundMovementPivotLocation_Acceleration_Offset;

	private static bool PredictGroundMovementPivotLocation_Velocity_IsValid;

	private static FFieldAddress PredictGroundMovementPivotLocation_Velocity_PropertyAddress;

	private static int PredictGroundMovementPivotLocation_Velocity_Offset;

	private static bool PredictGroundMovementPivotLocation_GroundFriction_IsValid;

	private static FFieldAddress PredictGroundMovementPivotLocation_GroundFriction_PropertyAddress;

	private static int PredictGroundMovementPivotLocation_GroundFriction_Offset;

	private static bool PredictGroundMovementPivotLocation_ReturnValue_IsValid;

	private static FFieldAddress PredictGroundMovementPivotLocation_ReturnValue_PropertyAddress;

	private static int PredictGroundMovementPivotLocation_ReturnValue_Offset;

	[UFunction(Flags = 348267521u)]
	[UMetaPath("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary:PredictGroundMovementStopLocation")]
	public unsafe static FVector PredictGroundMovementStopLocation(FVector Velocity, bool bUseSeparateBrakingFriction, float BrakingFriction, float GroundFriction, float BrakingFrictionFactor, float BrakingDecelerationWalking)
	{
		if (!PredictGroundMovementStopLocation_IsValid)
		{
			NativeReflection.LogInvalidFunctionAccessed("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary:PredictGroundMovementStopLocation");
			return default(FVector);
		}
		byte* ptr = stackalloc byte[(int)(uint)(PredictGroundMovementStopLocation_ParamsSize + 16)];
		int num = (int)((16L - (long)ptr) & 0xF);
		byte* ptr2 = ptr + num;
		Unsafe.InitBlockUnaligned(ptr2, 0, (uint)PredictGroundMovementStopLocation_ParamsSize);
		IntPtr intPtr = new IntPtr(ptr2);
		BlittableTypeMarshaler<FVector>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementStopLocation_Velocity_Offset), 0, PredictGroundMovementStopLocation_Velocity_PropertyAddress.Address, Velocity);
		BoolMarshaler.ToNative(IntPtr.Add(intPtr, PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_Offset), 0, PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_PropertyAddress.Address, bUseSeparateBrakingFriction);
		BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementStopLocation_BrakingFriction_Offset), 0, PredictGroundMovementStopLocation_BrakingFriction_PropertyAddress.Address, BrakingFriction);
		BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementStopLocation_GroundFriction_Offset), 0, PredictGroundMovementStopLocation_GroundFriction_PropertyAddress.Address, GroundFriction);
		BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementStopLocation_BrakingFrictionFactor_Offset), 0, PredictGroundMovementStopLocation_BrakingFrictionFactor_PropertyAddress.Address, BrakingFrictionFactor);
		BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementStopLocation_BrakingDecelerationWalking_Offset), 0, PredictGroundMovementStopLocation_BrakingDecelerationWalking_PropertyAddress.Address, BrakingDecelerationWalking);
		NativeReflection.InvokeStaticFunctionOptimized(classAddress, PredictGroundMovementStopLocation_FunctionAddress, intPtr, PredictGroundMovementStopLocation_ParamsSize);
		return BlittableTypeMarshaler<FVector>.FromNative(IntPtr.Add(intPtr, PredictGroundMovementStopLocation_ReturnValue_Offset), 0, PredictGroundMovementStopLocation_ReturnValue_PropertyAddress.Address);
	}

	[UFunction(Flags = 348267521u)]
	[UMetaPath("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary:PredictGroundMovementPivotLocation")]
	public unsafe static FVector PredictGroundMovementPivotLocation(FVector Acceleration, FVector Velocity, float GroundFriction)
	{
		if (!PredictGroundMovementPivotLocation_IsValid)
		{
			NativeReflection.LogInvalidFunctionAccessed("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary:PredictGroundMovementPivotLocation");
			return default(FVector);
		}
		byte* ptr = stackalloc byte[(int)(uint)(PredictGroundMovementPivotLocation_ParamsSize + 16)];
		int num = (int)((16L - (long)ptr) & 0xF);
		byte* ptr2 = ptr + num;
		Unsafe.InitBlockUnaligned(ptr2, 0, (uint)PredictGroundMovementPivotLocation_ParamsSize);
		IntPtr intPtr = new IntPtr(ptr2);
		BlittableTypeMarshaler<FVector>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementPivotLocation_Acceleration_Offset), 0, PredictGroundMovementPivotLocation_Acceleration_PropertyAddress.Address, Acceleration);
		BlittableTypeMarshaler<FVector>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementPivotLocation_Velocity_Offset), 0, PredictGroundMovementPivotLocation_Velocity_PropertyAddress.Address, Velocity);
		BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, PredictGroundMovementPivotLocation_GroundFriction_Offset), 0, PredictGroundMovementPivotLocation_GroundFriction_PropertyAddress.Address, GroundFriction);
		NativeReflection.InvokeStaticFunctionOptimized(classAddress, PredictGroundMovementPivotLocation_FunctionAddress, intPtr, PredictGroundMovementPivotLocation_ParamsSize);
		return BlittableTypeMarshaler<FVector>.FromNative(IntPtr.Add(intPtr, PredictGroundMovementPivotLocation_ReturnValue_Offset), 0, PredictGroundMovementPivotLocation_ReturnValue_PropertyAddress.Address);
	}

	static UAnimCharacterMovementLibrary()
	{
		if (UnrealTypes.CanLazyLoadNativeType(typeof(UAnimCharacterMovementLibrary)))
		{
			LoadNativeType();
		}
		UnrealTypes.OnCCtorCalled(typeof(UAnimCharacterMovementLibrary));
	}

	private static void LoadNativeType()
	{
		classAddress = NativeReflection.GetClass("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary");
		PredictGroundMovementStopLocation_FunctionAddress = NativeReflectionCached.GetFunction(classAddress, "PredictGroundMovementStopLocation");
		PredictGroundMovementStopLocation_ParamsSize = NativeReflection.GetFunctionParamsSize(PredictGroundMovementStopLocation_FunctionAddress);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementStopLocation_Velocity_PropertyAddress, PredictGroundMovementStopLocation_FunctionAddress, "Velocity");
		PredictGroundMovementStopLocation_Velocity_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementStopLocation_FunctionAddress, "Velocity");
		PredictGroundMovementStopLocation_Velocity_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementStopLocation_FunctionAddress, "Velocity", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_PropertyAddress, PredictGroundMovementStopLocation_FunctionAddress, "bUseSeparateBrakingFriction");
		PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementStopLocation_FunctionAddress, "bUseSeparateBrakingFriction");
		PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementStopLocation_FunctionAddress, "bUseSeparateBrakingFriction", Classes.FBoolProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementStopLocation_BrakingFriction_PropertyAddress, PredictGroundMovementStopLocation_FunctionAddress, "BrakingFriction");
		PredictGroundMovementStopLocation_BrakingFriction_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementStopLocation_FunctionAddress, "BrakingFriction");
		PredictGroundMovementStopLocation_BrakingFriction_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementStopLocation_FunctionAddress, "BrakingFriction", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementStopLocation_GroundFriction_PropertyAddress, PredictGroundMovementStopLocation_FunctionAddress, "GroundFriction");
		PredictGroundMovementStopLocation_GroundFriction_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementStopLocation_FunctionAddress, "GroundFriction");
		PredictGroundMovementStopLocation_GroundFriction_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementStopLocation_FunctionAddress, "GroundFriction", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementStopLocation_BrakingFrictionFactor_PropertyAddress, PredictGroundMovementStopLocation_FunctionAddress, "BrakingFrictionFactor");
		PredictGroundMovementStopLocation_BrakingFrictionFactor_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementStopLocation_FunctionAddress, "BrakingFrictionFactor");
		PredictGroundMovementStopLocation_BrakingFrictionFactor_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementStopLocation_FunctionAddress, "BrakingFrictionFactor", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementStopLocation_BrakingDecelerationWalking_PropertyAddress, PredictGroundMovementStopLocation_FunctionAddress, "BrakingDecelerationWalking");
		PredictGroundMovementStopLocation_BrakingDecelerationWalking_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementStopLocation_FunctionAddress, "BrakingDecelerationWalking");
		PredictGroundMovementStopLocation_BrakingDecelerationWalking_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementStopLocation_FunctionAddress, "BrakingDecelerationWalking", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementStopLocation_ReturnValue_PropertyAddress, PredictGroundMovementStopLocation_FunctionAddress, "ReturnValue");
		PredictGroundMovementStopLocation_ReturnValue_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementStopLocation_FunctionAddress, "ReturnValue");
		PredictGroundMovementStopLocation_ReturnValue_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementStopLocation_FunctionAddress, "ReturnValue", Classes.FStructProperty);
		PredictGroundMovementStopLocation_IsValid = PredictGroundMovementStopLocation_FunctionAddress != IntPtr.Zero && PredictGroundMovementStopLocation_Velocity_IsValid && PredictGroundMovementStopLocation_bUseSeparateBrakingFriction_IsValid && PredictGroundMovementStopLocation_BrakingFriction_IsValid && PredictGroundMovementStopLocation_GroundFriction_IsValid && PredictGroundMovementStopLocation_BrakingFrictionFactor_IsValid && PredictGroundMovementStopLocation_BrakingDecelerationWalking_IsValid && PredictGroundMovementStopLocation_ReturnValue_IsValid;
		NativeReflection.LogFunctionIsValid("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary:PredictGroundMovementStopLocation", PredictGroundMovementStopLocation_IsValid);
		PredictGroundMovementPivotLocation_FunctionAddress = NativeReflectionCached.GetFunction(classAddress, "PredictGroundMovementPivotLocation");
		PredictGroundMovementPivotLocation_ParamsSize = NativeReflection.GetFunctionParamsSize(PredictGroundMovementPivotLocation_FunctionAddress);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementPivotLocation_Acceleration_PropertyAddress, PredictGroundMovementPivotLocation_FunctionAddress, "Acceleration");
		PredictGroundMovementPivotLocation_Acceleration_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementPivotLocation_FunctionAddress, "Acceleration");
		PredictGroundMovementPivotLocation_Acceleration_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementPivotLocation_FunctionAddress, "Acceleration", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementPivotLocation_Velocity_PropertyAddress, PredictGroundMovementPivotLocation_FunctionAddress, "Velocity");
		PredictGroundMovementPivotLocation_Velocity_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementPivotLocation_FunctionAddress, "Velocity");
		PredictGroundMovementPivotLocation_Velocity_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementPivotLocation_FunctionAddress, "Velocity", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementPivotLocation_GroundFriction_PropertyAddress, PredictGroundMovementPivotLocation_FunctionAddress, "GroundFriction");
		PredictGroundMovementPivotLocation_GroundFriction_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementPivotLocation_FunctionAddress, "GroundFriction");
		PredictGroundMovementPivotLocation_GroundFriction_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementPivotLocation_FunctionAddress, "GroundFriction", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref PredictGroundMovementPivotLocation_ReturnValue_PropertyAddress, PredictGroundMovementPivotLocation_FunctionAddress, "ReturnValue");
		PredictGroundMovementPivotLocation_ReturnValue_Offset = NativeReflectionCached.GetPropertyOffset(PredictGroundMovementPivotLocation_FunctionAddress, "ReturnValue");
		PredictGroundMovementPivotLocation_ReturnValue_IsValid = NativeReflectionCached.ValidatePropertyClass(PredictGroundMovementPivotLocation_FunctionAddress, "ReturnValue", Classes.FStructProperty);
		PredictGroundMovementPivotLocation_IsValid = PredictGroundMovementPivotLocation_FunctionAddress != IntPtr.Zero && PredictGroundMovementPivotLocation_Acceleration_IsValid && PredictGroundMovementPivotLocation_Velocity_IsValid && PredictGroundMovementPivotLocation_GroundFriction_IsValid && PredictGroundMovementPivotLocation_ReturnValue_IsValid;
		NativeReflection.LogFunctionIsValid("/Script/AnimationLocomotionLibraryRuntime.AnimCharacterMovementLibrary:PredictGroundMovementPivotLocation", PredictGroundMovementPivotLocation_IsValid);
	}
}
