using System;
using System.Runtime.CompilerServices;
using UnrealEngine.Runtime;

namespace UnrealEngine.Plugins.EnhancedInput;

[UDelegate]
[UMetaPath("/Script/EnhancedInput.EnhancedInputActionHandlerDynamicSignature__DelegateSignature")]
public class FEnhancedInputActionHandlerDynamicSignature : FDelegate<FEnhancedInputActionHandlerDynamicSignature.Signature>
{
	public delegate void Signature(FInputActionValue ActionValue, float ElapsedTime, float TriggeredTime, UInputAction SourceAction);

	private static bool EnhancedInputActionHandlerDynamicSignature__DelegateSignature_IsValid;

	private static IntPtr EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress;

	private static int EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ParamsSize;

	private static bool EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_IsValid;

	private static FFieldAddress EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_PropertyAddress;

	private static int EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_Offset;

	private static bool EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_IsValid;

	private static FFieldAddress EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_PropertyAddress;

	private static int EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_Offset;

	private static bool EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_IsValid;

	private static FFieldAddress EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_PropertyAddress;

	private static int EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_Offset;

	private static bool EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_IsValid;

	private static FFieldAddress EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_PropertyAddress;

	private static int EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_Offset;

	public override Signature GetInvoker()
	{
		return Invoker;
	}

	static FEnhancedInputActionHandlerDynamicSignature()
	{
		LoadNativeType();
	}

	private static void LoadNativeType()
	{
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress = NativeReflection.GetFunction("/Script/EnhancedInput.EnhancedInputActionHandlerDynamicSignature__DelegateSignature");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ParamsSize = NativeReflection.GetFunctionParamsSize(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress);
		NativeReflectionCached.GetPropertyRef(ref EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_PropertyAddress, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "ActionValue");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_Offset = NativeReflectionCached.GetPropertyOffset(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "ActionValue");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_IsValid = NativeReflectionCached.ValidatePropertyClass(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "ActionValue", Classes.FStructProperty);
		NativeReflectionCached.GetPropertyRef(ref EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_PropertyAddress, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "ElapsedTime");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_Offset = NativeReflectionCached.GetPropertyOffset(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "ElapsedTime");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_IsValid = NativeReflectionCached.ValidatePropertyClass(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "ElapsedTime", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_PropertyAddress, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "TriggeredTime");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_Offset = NativeReflectionCached.GetPropertyOffset(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "TriggeredTime");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_IsValid = NativeReflectionCached.ValidatePropertyClass(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "TriggeredTime", Classes.FFloatProperty);
		NativeReflectionCached.GetPropertyRef(ref EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_PropertyAddress, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "SourceAction");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_Offset = NativeReflectionCached.GetPropertyOffset(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "SourceAction");
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_IsValid = NativeReflectionCached.ValidatePropertyClass(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress, "SourceAction", Classes.FObjectProperty);
		EnhancedInputActionHandlerDynamicSignature__DelegateSignature_IsValid = EnhancedInputActionHandlerDynamicSignature__DelegateSignature_FunctionAddress != IntPtr.Zero && EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_IsValid && EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_IsValid && EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_IsValid && EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_IsValid;
		NativeReflection.LogFunctionIsValid("/Script/EnhancedInput.EnhancedInputActionHandlerDynamicSignature__DelegateSignature", EnhancedInputActionHandlerDynamicSignature__DelegateSignature_IsValid);
	}

	private unsafe void Invoker(FInputActionValue ActionValue, float ElapsedTime, float TriggeredTime, UInputAction SourceAction)
	{
		if (!EnhancedInputActionHandlerDynamicSignature__DelegateSignature_IsValid)
		{
			NativeReflection.LogInvalidFunctionAccessed("/Script/EnhancedInput.EnhancedInputActionHandlerDynamicSignature__DelegateSignature");
		}
		else if (IsBound)
		{
			byte* ptr = stackalloc byte[(int)(uint)(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ParamsSize + 16)];
			int num = (int)((16L - (long)ptr) & 0xF);
			byte* ptr2 = ptr + num;
			Unsafe.InitBlockUnaligned(ptr2, 0, (uint)EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ParamsSize);
			IntPtr intPtr = new IntPtr(ptr2);
			NativeReflection.InitializeValue_InContainer(EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_PropertyAddress.Address, intPtr);
			FInputActionValue.ToNative(IntPtr.Add(intPtr, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_Offset), 0, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ActionValue_PropertyAddress.Address, ActionValue);
			BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_Offset), 0, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_ElapsedTime_PropertyAddress.Address, ElapsedTime);
			BlittableTypeMarshaler<float>.ToNative(IntPtr.Add(intPtr, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_Offset), 0, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_TriggeredTime_PropertyAddress.Address, TriggeredTime);
			UObjectMarshaler<UInputAction>.ToNative(IntPtr.Add(intPtr, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_Offset), 0, EnhancedInputActionHandlerDynamicSignature__DelegateSignature_SourceAction_PropertyAddress.Address, SourceAction);
			ProcessDelegate(intPtr);
		}
	}
}
