<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ILRuntime</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="ILRuntime.Mono.Cecil">
      <HintPath>..\..\ILRuntime.Mono.Cecil.dll</HintPath>
    </Reference>
    <Reference Include="ILRuntime.Mono.Cecil.Pdb">
      <HintPath>..\..\ILRuntime.Mono.Cecil.Pdb.dll</HintPath>
    </Reference>
    <Reference Include="ILRuntime.Mono.Cecil.Mdb">
      <HintPath>..\..\ILRuntime.Mono.Cecil.Mdb.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>