<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GSE.GSSdk</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="ILRuntime">
      <HintPath>..\..\GameDll\ILRuntime.dll</HintPath>
    </Reference>
    <Reference Include="Google.Protobuf">
      <HintPath>..\..\GameDll\Google.Protobuf.dll</HintPath>
    </Reference>
    <Reference Include="LitJson">
      <HintPath>..\..\GameDll\LitJson.dll</HintPath>
    </Reference>
    <Reference Include="GSE.OnlineBase">
      <HintPath>..\..\GameDll\GSE.OnlineBase.dll</HintPath>
    </Reference>
    <Reference Include="UnrealEngine.Runtime">
      <HintPath>..\..\GameDll\UnrealEngine.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="b1.Native">
      <HintPath>..\..\GameDll\b1.Native.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>