using UnrealEngine.Runtime;

namespace b1;

[UEnum]
[BlueprintType]
[UMetaPath("/Script/b1.EBGUFSMEventName", "b1", UnrealModuleType.Game)]
public enum EBGUFSMEventName : byte
{
	FSM_EVENT_LIFE_HASTARGET = 0,
	FSM_EVENT_LIFE_GOHOME = 10,
	FSM_EVENT_LIFE_ARRIVEHOME = 11,
	FSM_EVENT_LIFE_GAZEANDSURROUND = 12,
	FSM_EVENT_LIFE_DIE = 1,
	FSM_EVENT_LIFE_REVIVE = 2,
	FSM_EVENT_LIFE_STANDBY = 3,
	FSM_EVENT_NONCOMBAT_WARNNING = 4,
	FSM_EVENT_NONCOMBAT_IDLE = 5,
	FSM_EVENT_BATTLE_BEHIT = 6,
	FSM_EVENT_BATTLE_ATTACK = 7,
	FSM_EVENT_BATTLE_WANDER = 8,
	FSM_EVENT_BATTLE_STALEMATE = 9
}
