using UnrealEngine.Runtime;

namespace b1;

[UEnum]
[BlueprintType]
[UMetaPath("/Script/b1.EBGUFSMStateName", "b1", UnrealModuleType.Game)]
public enum EBGUFSMStateName : byte
{
	FSM_STATE_LIFE = 0,
	FSM_STATE_LIFE_RETURNHOME = 9,
	FSM_STATE_LIFE_DEAD = 1,
	FSM_STATE_BATTLE = 2,
	FSM_STATE_BATTLE_ATTACK = 3,
	FSM_STATE_BATTLE_WANDER = 4,
	FSM_STATE_BATTLE_STALEMATE = 5,
	FSM_STATE_NONCOMBAT = 6,
	FSM_STATE_NONCOMBAT_WARNNING = 7,
	FSM_STATE_NONCOMBAT_IDLE = 8,
	FSM_STATE_REVOLVEAROUND = 11,
	FSM_STATE_NEUTRALANIMAL_PATROL = 12,
	FSM_STATE_NEUTRALANIMAL_BATTLE = 13,
	FSM_STATE_NEUTRALANIMAL_ESCAPE = 14,
	FSM_STATE_INVALID = 20
}
