namespace b1.BGW;

public enum EPreloadAssetSourceType
{
	None = 0,
	All = 1,
	NoPreload = 2,
	GlobalResource_All = 101,
	GlobalResource_Level = 102,
	GlobalResource_Common = 103,
	GlobalResource_End = 199,
	UIResource_All = 201,
	UIResource_NoCache = 202,
	UIResource_ReleaseInMain = 203,
	UIResource_ReleaseInChangeLevel = 204,
	UIResource_End = 299,
	MonsterResource_All = 301,
	MonsterResource_Instances = 302,
	MonsterResource_Comm = 303,
	MonsterResource_BeAttacked = 304,
	MonsterResource_DeathDisp = 305,
	MonsterResource_End = 399,
	PlayerResource_All = 401,
	PlayerResource_Instances = 402,
	PlayerResource_Comm = 403,
	PlayerResource_BeAttacked = 404,
	PlayerResource_DeathDisp = 405,
	PlayerResource_Ability_All = 471,
	PlayerResource_Ability_Talent = 472,
	PlayerResource_Ability_FaBao = 473,
	PlayerResource_Ability_Magic = 474,
	PlayerResource_Ability_Vigor = 475,
	PlayerResource_Ability_End = 489,
	PlayerResource_End = 499,
	Other_All = 501,
	Other_Interact = 502,
	Other_DynamicObstaclePerform = 503,
	Other_TamerMonsterClassNoCache = 504,
	Other_End = 599,
	End = 999
}
