<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>b1.NativePlugins</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnrealEngine.Runtime">
      <HintPath>..\..\UnrealEngine.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="UnrealEngine">
      <HintPath>..\..\UnrealEngine.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>..\..\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>