using b1.CppExport;

namespace b1;

public static class GameplayTagFuncLib
{
	public static GSE_NativeGameplayTagFuncs.Del_MakeGameplayTagFromName MakeGameplayTagFromName;

	public static GSE_NativeGameplayTagFuncs.Del_MakeGameplayTagFromString MakeGameplayTagFromString;

	public static GSE_NativeGameplayTagFuncs.Del_EqualEqual_GameplayTag EqualEqual_GameplayTag;

	public static GSE_NativeGameplayTagFuncs.Del_NotEqual_GameplayTag NotEqual_GameplayTag;

	public static GSE_NativeGameplayTagFuncs.Del_IsGameplayTagValid IsGameplayTagValid;

	public static GSE_NativeGameplayTagFuncs.Del_GetTagName GetTagName;

	public static GSE_NativeGameplayTagFuncs.Del_MakeLiteralGameplayTag MakeLiteralGameplayTag;

	public static GSE_NativeGameplayTagFuncs.Del_NotEqual_TagTag NotEqual_TagTag;

	public static GSE_NativeGameplayTagFuncs.Del_GetDebugStringFromGameplayTag GetDebugStringFromGameplayTag;

	public static GSE_NativeGameplayTagFuncs.Del_AddGamePlayTagToINI AddGamePlayTagToINI;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_Allocate GameplayTagContainerRef_Allocate;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_Destroy GameplayTagContainerRef_Destroy;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_AddTag GameplayTagContainerRef_AddTag;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_RemoveTag GameplayTagContainerRef_RemoveTag;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_HasTag GameplayTagContainerRef_HasTag;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_HasTagName GameplayTagContainerRef_HasTagName;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_GetTag GameplayTagContainerRef_GetTag;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_FilterTags GameplayTagContainerRef_FilterTags;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_FilterTag GameplayTagContainerRef_FilterTag;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_GetNum GameplayTagContainerRef_GetNum;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_IsValid GameplayTagContainerRef_IsValid;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_IsEmpty GameplayTagContainerRef_IsEmpty;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_MatchesAnyTags GameplayTagContainerRef_MatchesAnyTags;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_HasAnyTags GameplayTagContainerRef_HasAnyTags;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_HasAllTags GameplayTagContainerRef_HasAllTags;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_EqualEqual GameplayTagContainerRef_EqualEqual;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_NotEqual GameplayTagContainerRef_NotEqual;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_MakeLiteralGameplayTagContainer GameplayTagContainerRef_MakeLiteralGameplayTagContainer;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_MakeGameplayTagContainerFromTag GameplayTagContainerRef_MakeGameplayTagContainerFromTag;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_NotEqual_TagContainerTagContainer GameplayTagContainerRef_NotEqual_TagContainerTagContainer;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_GetDebugStringFromGameplayTagContainer GameplayTagContainerRef_GetDebugStringFromGameplayTagContainer;

	public static GSE_NativeGameplayTagFuncs.Del_GameplayTagContainerRef_Append GameplayTagContainerRef_Append;

	static GameplayTagFuncLib()
	{
		new GSE_NativeGameplayTagFuncs();
	}
}
